contentful/field-editors

.dependabot/config.yml
To get updates automatically on weekly basis.
=> ci: 🎡 enable dependabot

packages/checkbox/src/CheckboxEditor.mdx, packages/dropdown/src/DropdownEditor.mdx, packages/radio/src/RadioEditor.mdx
this confused people (including Stefan) because it kind of looks like the docs are broken :)
It seems like there were unit tests for these features anyway, and no cypress tests - so we're not losing coverage.
=> feat: remove no config views from doc-appz

packages/markdown/src/MarkdownEditor.mdx, packages/reference/src/entries/SingleEntryReferenceEditor.mdx, packages/rich-text/src/RichTextEditor.mdx
=> docs: add examples of complex editors as field extensions

packages/rich-text/src/setupTests.js
=> fix: add regenerator-runtime to jest setup script

extensions/entry-extension-collapsible/package.json, extensions/entry-extension-collapsible/src/Field.tsx, extensions/entry-extension-collapsible/src/styles.ts, extensions/markdown-extension/package.json, extensions/multiple-references-extension/package.json, extensions/rich-text-extension/package.json, extensions/singleline-extension/package.json, packages/_shared/package.json, packages/_test/package.json, packages/reference/package.json, yarn.lock
This demonstrates the new schema error events working for entry fields. :)
=> feat: show errors in collapsible fields extension

extensions/entry-extension-collapsible/src/Field.tsx, extensions/entry-extension-collapsible/src/shared.tsx, packages/validation-errors/src/ValidationErrors.tsx, packages/validation-errors/src/styles.ts
=> refactor: improve validation-errors

.circleci/config.yml, lerna.json
Adds a new CircleCI job `release` which uses `lerna version` and `lerna publish` to release changes.
=> ci: setup auto-release on master commit

packages/reference/.eslintrc.js, packages/reference/src/common/MultipleReferenceEditor.tsx, packages/reference/src/common/ReferenceEditor.tsx, packages/reference/src/common/SingleReferenceEditor.tsx, packages/reference/src/components/LinkActions/LinkActions.tsx, packages/reference/src/components/LinkActions/LinkEntityActions.tsx, packages/reference/src/types.ts
Allow overriding `Create and link entry`, `Link existing entry` with custom labels.
=> feat: 🎸 allow to override link & create action labels

cypress/integration/MultipleMediaEditor.spec.ts, packages/reference/src/assets/MultipleMediaEditor.mdx, packages/reference/src/assets/SingleMediaEditor.mdx, packages/reference/src/common/MultipleReferenceEditor.tsx, packages/reference/src/common/ReferenceEditor.tsx, packages/reference/src/common/SingleReferenceEditor.tsx, packages/reference/src/components/LinkActions/LinkActions.tsx, packages/reference/src/components/LinkActions/LinkEntityActions.tsx
Add render prop to provide override for reference actions.
=> feat: 🎸 customize actions on reference editors

packages/reference/src/common/MultipleReferenceEditor.tsx, packages/reference/src/common/SingleReferenceEditor.tsx, packages/reference/src/components/LinkActions/LinkActions.tsx, packages/reference/src/components/LinkActions/LinkEntityActions.tsx, packages/reference/src/index.tsx, packages/reference/src/types.ts
Minor clean up to ease consumption of reference editor.
=> fix: clarify multiple prop

cypress/integration/LocationEditor.spec.ts
Should result in green ci again.
=> fix: 🐛 flaky location editor test

cypress/integration/MarkdownEditorInsertTable.spec.ts, cypress/integration/MarkdownEditorSpecialCharacter.spec.ts, package.json, packages/reference/package.json, packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx, yarn.lock
Bump Forma to utilise the size=auto in references.
=> chore: 🤖 bump @contentful/forma-36-react-components

cypress/integration/MarkdownEditorSpecialCharacter.spec.ts
Use `findByText` to be more reliable.
=> fix: flaky markdown test

packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.tsx, packages/reference/src/components/LinkActions/CombinedLinkActions.tsx, packages/reference/src/components/LinkActions/redesignStyles.ts, packages/reference/src/components/LinkActions/styles.ts
Makes `CombinedLinkActions` actions bold and removes underline text decoration as per design request.
=> feat: 🎸 improve CombinedLinkActions styles

packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.tsx, packages/reference/src/components/LinkActions/CombinedLinkActions.tsx, packages/reference/src/components/LinkActions/LinkActions.tsx, packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
This PR adds a custom combined link action label
=> feat: add custom combined link action label

packages/rich-text/src/Toolbar/index.js
=> fix: do not call set state on unmounted rich-text

extensions/entry-extension-collapsible/package.json, extensions/markdown-extension/package.json, extensions/multiple-references-extension/package.json, extensions/rich-text-extension/package.json, extensions/singleline-extension/package.json, package.json, packages/boolean/package.json, packages/checkbox/package.json, packages/date/package.json, packages/default-field-editors/package.json, packages/dropdown/package.json, packages/json/package.json, packages/list/package.json, packages/location/package.json, packages/markdown/package.json, packages/multiple-line/package.json, packages/number/package.json, packages/radio/package.json, packages/rating/package.json, packages/reference/package.json, packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx, packages/rich-text/package.json, packages/single-line/package.json, packages/slug/package.json, packages/tags/package.json, packages/url/package.json, packages/validation-errors/package.json, yarn.lock
3.63.5 has the new dropdown positioning.
Resolves #188
Resolves #415
=> chore: bump forma-36-react-components to 3.63.6

packages/reference/src/components/LinkActions/CombinedLinkActions.tsx, packages/reference/src/components/LinkActions/LinkActions.tsx
Fix spacings by wrapping dropdown correctly.
=> fix: 🐛 add missing DropdownList component

packages/markdown/src/MarkdownEditor.tsx, packages/markdown/src/components/MarkdownPreview/MarkdownPreview.tsx, packages/markdown/src/components/MarkdownTextarea/CodeMirrorWrapper.ts, packages/markdown/src/components/MarkdownTextarea/MarkdownTextarea.tsx, packages/rich-text/src/RichTextEditor.jsx
* feat(markdown-editor): add minHeight prop
* feat(rich-text-editor): add minHeight prop
=> feat: minHeight props

packages/rich-text/src/RichTextEditor.jsx
Use `oneOfType` instead of `oneOf` when approporiate.
=> fix: use correct prop types

extensions/entry-extension-collapsible/package.json, extensions/markdown-extension/package.json, extensions/multiple-references-extension/package.json, extensions/rich-text-extension/package.json, extensions/singleline-extension/package.json, packages/_shared/package.json, packages/_shared/src/FieldConnector.ts, packages/_test/package.json, packages/markdown/src/MarkdownActions.ts, packages/reference/package.json, packages/slug/src/SlugEditor.tsx, packages/slug/src/TrackingFieldConnector.tsx, yarn.lock
Upgrade UIE-sdk and fix some type errors that arose from the upgrade. In some cases I've chosen to use `BaseExtensionSDK & SharedEditorSDK` as this seems to best reflect what these components expect.
=> chore: [] Upgrade uie sdk

package.json, yarn.lock
Required for: https://github.com/contentful/field-editors/pull/610
=> chore: [EXT-2496] allow resolving new major version of typescript

packages/_test/package.json, packages/default-field-editors/package.json
Correct the `module` field of `package.json` to point to the correct esm files.
=> fix(_test,default-field-editors): correct esm entry file

packages/rich-text/src/RichTextEditor.mdx, packages/rich-text/src/RichTextEditor.styles.ts, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/Toolbar/StickyToolbarWrapper.tsx, packages/rich-text/src/Toolbar/index.tsx
Ports over styles from current RT editor to the alpha RT editor
=> feat: tidy alpha rt editor styles

packages/rich-text/package.json
Fixes https://github.com/contentful/field-editors/issues/715
=> chore: fix rich text version to v14.1.2

cypress/integration/RichTextEditor.spec.ts, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/Toolbar/index.tsx, packages/rich-text/src/hooks/useCustomEditor.ts, packages/rich-text/src/plugins/Bold/index.tsx, packages/rich-text/src/plugins/Code/index.tsx, packages/rich-text/src/plugins/Editor/index.ts, packages/rich-text/src/plugins/Hr/index.tsx, packages/rich-text/src/plugins/Italic/index.tsx, packages/rich-text/src/plugins/Marks/index.tsx, packages/rich-text/src/plugins/Underline/index.tsx, packages/rich-text/src/types.ts
=> feat: add HR component support

cypress.json, cypress/integration/RichTextEditor.spec.ts, cypress/support/index.d.ts, packages/rich-text/src/RichTextEditor.styles.ts, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/Toolbar/index.tsx, packages/rich-text/src/plugins/Editor/index.ts, packages/rich-text/src/plugins/Heading/index.tsx, packages/rich-text/src/types.ts
=> feat: add support for headings [SHE-16]

cypress/integration/RichTextEditor.spec.ts, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/Toolbar/index.tsx, packages/rich-text/src/plugins/Editor/index.ts, packages/rich-text/src/plugins/Quote/index.tsx
This PR adds the blockquote plugin to the new version of the Rich Text Editor
=> feat: rich text blockquote plugin

.github/workflows/auto-approve.yml
See https://github.com/hmarr/auto-approve-action/releases/tag/v2.1.0
=> ci: fix auto-approve gh workflow

packages/_shared/package.json, packages/_test/package.json, packages/reference/package.json
really this commit exists to test the pipeline
=> feat: [] bump forma tokens

packages/rich-text/package.json, packages/rich-text/src/RichTextEditor.styles.ts, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/plugins/Heading/index.tsx, packages/rich-text/src/plugins/Hr/index.tsx, packages/rich-text/src/plugins/List/index.tsx, packages/rich-text/src/plugins/Paragraph/index.tsx, yarn.lock
Adds basic paragraph styling support and fix a few issues I've found.
=> feat: add paragraph for slatejs next []

cypress/integration/RichTextEditor.spec.ts, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/Toolbar/index.tsx, packages/rich-text/src/plugins/Quote/index.tsx
This PR ports over the quote plugin to use slate-plugins
=> refactor(rteditor): port quote plugin to slate-plugins

cypress/integration/RichTextEditor.spec.ts, package.json, packages/json/src/JsonEditoField.tsx, packages/reference/src/common/MultipleReferenceEditor.tsx, packages/reference/src/components/LinkActions/LinkActions.tsx, packages/reference/src/components/LinkActions/LinkEntityActions.tsx, packages/rich-text/package.json, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/helpers/editor.ts, packages/rich-text/src/plugins/Heading/index.tsx, packages/rich-text/src/plugins/Hr/index.tsx, packages/rich-text/src/plugins/Quote/index.tsx, packages/rich-text/src/plugins/Table/helpers.ts, packages/rich-text/src/plugins/Table/index.tsx, packages/rich-text/src/types.ts, yarn.lock
=> feat: add table markup

packages/rich-text/package.json
Needed to support the rich text editor in some client applications
=> fix: add peer dependencies

.github/CODEOWNERS, .github/auto_assign.yml
Adds Contentful teams as owners of specific folders in the project.
=> chore: added CODEOWNERS file

packages/rich-text/src/Toolbar/index.tsx, packages/rich-text/src/helpers/editor.ts, packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx, packages/rich-text/src/plugins/Hyperlink/index.tsx
=> feat: add hyperlink (only adding regular hyperlinks)

packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/helpers/sanitizeSlateDoc.ts, packages/rich-text/src/types.ts
Ensures text nodes never get added to the document structure in a way that clashes with the validation layer.
=> fix: orphaned text nodes

packages/rich-text/src/helpers/editor.ts, packages/rich-text/src/plugins/Heading/index.tsx, packages/rich-text/src/plugins/Hr/index.tsx, packages/rich-text/src/plugins/Hyperlink/FetchingWrappedAssetCard.tsx, packages/rich-text/src/plugins/Hyperlink/FetchingWrappedEntryCard.tsx, packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx, packages/rich-text/src/plugins/Hyperlink/index.tsx, packages/rich-text/src/plugins/List/index.tsx, packages/rich-text/src/types.ts
=> feat: add support for entry and asset hyperlinks

.circleci/config.yml, lerna.json, packages/rich-text/package.json
Reverts contentful/field-editors#782
That didn't work exactly as expected. Reverting for now
=> chore: revert "auto publish alpha Rich Text package"

packages/multiple-line/src/MultipleLineEditor.mdx, packages/multiple-line/src/MultipleLineEditor.tsx, packages/multiple-line/src/styles.ts
Showing the character count for multiline fields with opt-out possibility through additional prop.
✅ Closes: #491
=> feat: 🎸 add char counter

packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
One more attempt to fix: https://github.com/contentful/field-editors/pull/792
=> fix: focus on search input

packages/rich-text/src/helpers/deserializer.ts, packages/rich-text/src/plugins/Bold/index.tsx, packages/rich-text/src/plugins/Code/index.tsx, packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx, packages/rich-text/src/plugins/EmbeddedEntityBlock/index.tsx, packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx, packages/rich-text/src/plugins/Heading/index.tsx, packages/rich-text/src/plugins/Hr/index.tsx, packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx, packages/rich-text/src/plugins/Hyperlink/index.tsx, packages/rich-text/src/plugins/Paragraph/index.tsx, packages/rich-text/src/plugins/Quote/index.tsx
=> feat: add suport for deserialization

cypress/integration/LocationEditor.spec.ts
Google Maps service started returning a different value.
=> test: fix google maps location address

cypress/integration/RichTextEditor.spec.ts, packages/rich-text/src/helpers/editor.ts, packages/rich-text/src/plugins/Heading/index.tsx, packages/rich-text/src/plugins/Hr/index.tsx, packages/rich-text/src/plugins/List/index.tsx
It unwraps blockquote when trying to add one of those types inside a blockquote:
- Heading
- List (UL, OL)
- HR
=> fix: blockquote wrapping/unwrapping buggy

apps/entry-app-collapsible/package.json, apps/entry-app-collapsible/src/FieldGroupsEditor.tsx, apps/entry-app-collapsible/src/index.tsx, package.json, packages/_shared/src/ModalDialogLauncher.tsx, packages/markdown/src/components/MarkdownToolbar.tsx, packages/markdown/src/dialogs/CheatsheetModalDialog.tsx, packages/markdown/src/dialogs/ConfirmInsertAssetModalDialog.tsx, packages/markdown/src/dialogs/EmdebExternalContentDialog.tsx, packages/markdown/src/dialogs/InsertLinkModalDialog.tsx, packages/markdown/src/dialogs/InsertTableModalDialog.tsx, packages/markdown/src/dialogs/SpecialCharacterModalDialog.tsx, packages/markdown/src/utils/userAgent.ts, packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.spec.tsx, packages/rich-text/src/RichTextEditor.jsx, packages/rich-text/src/dialogs/HypelinkDialog/HyperlinkDialog.jsx, yarn.lock
=> feat: Integrate Modal v4

packages/rich-text/src/plugins/Hyperlink/index.tsx
Hotfix for a bug that's unfortunately tough to pick out without getting run through validation.
=> fix: hyperlink paste deserialization

apps/entry-app-collapsible/src/FieldGroupsEditor.tsx, packages/markdown/src/components/MarkdownBottomBar.tsx, packages/markdown/src/dialogs/CheatsheetModalDialog.tsx, packages/markdown/src/dialogs/ConfirmInsertAssetModalDialog.tsx, packages/markdown/src/dialogs/SpecialCharacterModalDialog.tsx, packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.tsx, packages/reference/src/components/LinkActions/NoLinkPermissionsInfo.tsx, packages/reference/src/components/MissingEntityCard/MissingEntityCard.tsx, packages/reference/src/components/ScheduledIconWithTooltip/ScheduleTooltip.tsx, packages/rich-text/src/plugins/CommandPalette/CommandPanel/CommandPanelMenu.js, packages/slug/src/SlugEditorField.tsx, packages/tags/src/TagsEditorConstraints.tsx
Migrates all typography components to v4
=> feat: typography v4 migration

packages/rich-text/src/plugins/Table/index.tsx
Fixes an issue in which tables pasted from elsewhere are unfortunately not internally [normalized](https://docs.slatejs.org/concepts/11-normalizing) by the work we are doing in [`sanitizeSlateDoc`](https://github.com/contentful/field-editors/blob/next/packages/rich-text/src/RichTextEditor.tsx#L159), since this is invoked on the value passed to the editor and not the internal editor value (cf. https://github.com/ianstormtaylor/slate/issues/2206).
So, conceptually this is identical to the work described [here](https://github.com/contentful/field-editors/blob/dbdf212c8b18768094ab055d7ca13c064b075ac3/packages/rich-text/src/helpers/sanitizeSlateDoc.ts#L33-L59), only on a much more granular level: orphaned text nodes are wrapped by a paragraph. This approach works perfectly well for hyperlinks, …
=> fix: pasted tables

packages/rich-text/src/plugins/Paste/sanitizers/sanitizeTables.tsx
Extends our table paste logic from https://github.com/contentful/field-editors/pull/854 to disallow table captions.
The default behavior is for `<caption />` elements to be intercepted by the Slate parser and rendered as span elements within the table. This is incompatible with the validation layer, which expects only row child elements.
This is probably not ideal behavior in the long run: we may want to reinsert the caption as a `BLOCKS.PARAGRAPH` outside the table, for example, or to add support for table captions as a first class element. In the short term, this is a simple fix ensure pasting tables does not break the validation layer and require refresh when the editor is in embedded environments that are coupled to the CMA.
=> fix: disallow table captions

packages/default-field-editors/src/DefaultFieldEditors.mdx, packages/markdown/src/MarkdownEditor.mdx, packages/reference/src/assets/MultipleMediaEditor.mdx, packages/reference/src/assets/SingleMediaEditor.mdx, packages/reference/src/entries/MultipleEntryReferenceEditor.mdx, packages/reference/src/entries/SingleEntryReferenceEditor.mdx, packages/rich-text/src/plugins/Hyperlink/Hyperlink.js
Small changes in mdx examples (codemod can't handle them)
=> chore: small adjustments

packages/rich-text/src/plugins/Table/index.tsx
=> fix: tables pasting on elements with content

packages/checkbox/src/CheckboxEditor.spec.tsx, packages/checkbox/src/CheckboxEditor.tsx, packages/markdown/src/dialogs/EmdebExternalContentDialog.tsx
Replace CheckboxField from v3 with Checkbox
There are no `<Checkbox />` from v3 in the codebase
=> feat: Checkbox v4 adoption

package.json, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/plugins/List/index.tsx, patches/@udecode+plate-list+3.5.1.patch, yarn.lock
Done by passing the list of all blocks to `validLiChildrenTypes` list plugin and additionally by patching it, the plugin doesn't change the element if it's in that list.
=> feat: enable block elements in list items

packages/rich-text/src/RichTextEditor.jsx
Specify a CSS font-family for the RTE.
=> fix(rich-text-editor): specify font-family

.circleci/config.yml
This runs the integration tests on more browsers.
=> ci: integration tests via matrix

cypress/integration/rich-text/RichTextEditor.spec.ts, packages/rich-text/src/plugins/InsertBeforeFirstVoidBlock/index.tsx
It adds a paragraph between blocks if siblings. 
The current behavior selects the next embedded block if they are siblings.
=> fix: embedded block between paragraphs []

packages/rich-text/src/plugins/Paragraph/index.tsx
[SHE-561](https://contentful.atlassian.net/browse/SHE-561)
=> fix: deserialize different lines as multiple paragraphs

cypress/integration/rich-text/RichTextEditor.Pasting.spec.ts
The issue with copy & pasting hyperlinks is fixed by https://github.com/contentful/field-editors/pull/949. That broke other stuff but for now, let's have a test to make sure pasting hyperlinks will continue to work.
=> test(rich-text): add a test for pasting hyperlinks

cypress/integration/rich-text/RichTextEditor.spec.ts, cypress/integration/rich-text/RichTextPage.ts, packages/rich-text/package.json, packages/rich-text/src/RichTextEditor.mdx, packages/rich-text/src/test-utils/toContentfulError.ts, packages/rich-text/src/test-utils/validation.ts, yarn.lock
=> chore(docz): validate against Rich Text schema

.circleci/config.yml, .gitignore, package.json, yarn.lock
=> build: use turborepo

cypress/integration/rich-text/RichTextEditor.Pasting.spec.ts, cypress/integration/rich-text/__snapshots__/RichTextEditor.Pasting.spec.ts.snap, packages/rich-text/src/RichTextEditor.tsx, packages/rich-text/src/plugins/index.ts
Reordering AST deserializer & HTML deserializer fixes the issue.
=> fix: basic marks deserialization

cypress/integration/rich-text/RichTextEditor.spec.ts, cypress/integration/rich-text/documentWithLinks.js, cypress/support/commands.js, cypress/support/index.d.ts, packages/rich-text/src/RichTextEditor.mdx, packages/rich-text/src/TrackingProvider.tsx, packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx, packages/rich-text/src/plugins/EmbeddedEntityBlock/index.tsx, packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx, packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx, packages/rich-text/src/plugins/Hyperlink/index.tsx, packages/rich-text/src/plugins/index.ts, packages/rich-text/src/plugins/links-tracking.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
Restore tracking of linked entities rendering in the new rich text editor
=> feat: entry fetched callback in links

packages/rich-text/src/ContentfulEditorProvider.ts
Reverting the change until we figure a better solution.
=> fix(rich-text): revert back id change

cypress/integration/rich-text/RichTextEditor.Pasting.spec.ts, cypress/integration/rich-text/__snapshots__/RichTextEditor.Pasting.spec.ts.snap, packages/rich-text/src/plugins/Quote/createQuotePlugin.ts
Break a paragraph when pasting a blockquote in between
=> fix: pasting blockquote

cypress/integration/rich-text/RichTextEditor.Pasting.spec.ts
Tries to make text selection consistent in blockquote pasting test
=> test: fix non-passing test in ci

cypress/integration/rich-text/RichTextEditor.Tracking.spec.ts, cypress/integration/rich-text/RichTextPage.ts
Follow up PR for https://github.com/contentful/field-editors/pull/1027
=> test(rte-tracking): add tests when cancelling embeds []

packages/rich-text/src/helpers/editor.ts, packages/rich-text/src/plugins/Heading/components/ToolbarHeadingButton.tsx, packages/rich-text/src/plugins/List/components/ToolbarListButton.tsx, packages/rich-text/src/plugins/List/utils.ts, packages/rich-text/src/plugins/Quote/__test__/createQuotePlugin.test.tsx, packages/rich-text/src/plugins/Quote/components/Quote.tsx, packages/rich-text/src/plugins/Quote/createQuotePlugin.ts
=> fix(rich-text): quick fixes

packages/rich-text/src/plugins/Quote/toggleQuote.ts, packages/rich-text/src/plugins/Text/createTextPlugin.ts
**Note:** I'd appreciate it if you could play around with it on the preview deployment to check for any unusual side effects. Thanks.
=> fix(rich-text): unhang triple selection ranges

packages/rich-text/src/plugins/Text/createTextPlugin.ts
This implementation should remove only the first paragraph when empty, it acts as pressing `delete`, other paragraph and headings deletion will be handled by the paragraph and heading original plugins when pressing `delete` and `backspace` because of their different behavior.
=> fix(rte): pressing backspace on empty paragraphs

cypress/integration/rich-text/RichTextEditor.spec.ts, packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx
=> fix(rich-text): show inline entry CT as tooltip

cypress/integration/rich-text/RichTextLists.spec.ts, cypress/integration/rich-text/__snapshots__/RichTextLists.spec.ts.snap, packages/rich-text/src/plugins/List/transforms/toggleList.ts, packages/rich-text/src/plugins/List/transforms/unwrapList.ts
Fix behaviour of raising list items when switching a list off
=> fix: untoggling list

packages/rich-text/src/plugins/Table/addTableTrackingEvents.ts, packages/rich-text/src/plugins/Tracking/createTrackingPlugin.ts
=> feat(rich-text): log pasting of invalid table content

packages/rich-text/package.json, packages/rich-text/src/plugins/Table/insertTableFragment.ts, yarn.lock
Fixed by upgrading to the latest Slate release
=> fix(rich-text): soft breaks (shift + enter) doesn't work

cypress/integration/rich-text/RichTextEditor.spec.ts, packages/rich-text/package.json, packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx, packages/rich-text/src/plugins/shared/EntityStatusIcon.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx, packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedAssetCard.test.tsx, packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedEntryCard.test.tsx, yarn.lock
Temporarily reverting contentful/field-editors#1135 as it seems to cause more issues than it fixes. I will consider bringing it back later
=> fix: revert "fix(rich-text): avoid page freeze when loading entities"

packages/rich-text/package.json, yarn.lock
Already been released but I forgot to open this PR
=> chore(release): publish rich-text v2.0.0-next.42

packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx, packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
This fixes issues in the RT e.g. pressing Enter on a card doesn't work as expected + drag & drop issues
=> fix: don't register onClick callbacks when isClickable is false

packages/_test/package.json, packages/_test/src/createFakeCMAAdapter.ts, packages/_test/src/index.ts, packages/reference/package.json, packages/reference/src/__fixtures__/FakeSdk.ts, packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx, packages/reference/src/common/EntityStore.ts, packages/reference/src/entries/SortableElements.tsx, packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx, packages/reference/src/types.ts, packages/rich-text/src/RichTextEditor.mdx, packages/rich-text/src/plugins/EmbeddedEntityBlock/FetchingWrappedAssetCard.js, packages/rich-text/src/plugins/EmbeddedEntityBlock/FetchingWrappedEntryCard.js, packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx, packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedAssetCard.test.tsx, packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedEntryCard.test.tsx, packages/rich-text/src/plugins/shared/useFetchedEntity.ts, yarn.lock
Add an additional loading function to the `useEntities` hook in order to get info about external resources from other spaces.
=> feat: add simple fetching for resources

packages/reference/src/assets/MultipleMediaEditor.tsx, packages/reference/src/entries/MultipleEntryReferenceEditor.tsx
Yet another fix for drilling the props for the reference editor.
=> fix: drill props correctly

packages/reference/src/common/EntityStore.ts
Fix: check for the env alias in the field editor reference.
=> fix: check the env alias for the field editor reference [ZEND-2488]

packages/reference/src/components/MissingEntityCard/MissingEntityCard.tsx, packages/reference/src/components/MissingEntityCard/styles.ts
=> style: fix missing entry card styles [TOL-188]

packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
Handle accessing undefined value for version compare in webapp
=> fix: version compare [TOL-339]

packages/reference/src/components/LinkActions/LinkEntityActions.tsx
https://contentful.atlassian.net/browse/ZEND-2500
=> fix: introduce callback to properly handle available content types [ZEND-2500]

packages/rich-text/src/plugins/shared/useFetchedEntity.ts
Check if store is undefined to return early in useFetchedEntity to fix issue with version compare in web app
=> fix: check store in entity fetch

packages/rich-text/src/plugins/shared/useFetchedEntity.ts
Update hooks deps for useFetchedEntity when store is available to load in assets in compare version in webapp
=> fix: update hooks deps in useFetchedEntity [TOL-339]

packages/reference/src/assets/MultipleMediaEditor.tsx, packages/reference/src/assets/SingleMediaEditor.tsx
Display the props documentation
=> fix: change the props type definitions

packages/date/src/DatepickerInput.tsx
=> fix: fix date-editor import

cypress/integration/DateEditor.spec.ts, packages/date/package.json, packages/date/src/DatepickerInput.spec.tsx, yarn.lock
Cover with tests following cases: 
- https://github.com/contentful/field-editors/pull/1239
- https://github.com/contentful/field-editors/pull/1255
=> test: add tests for field-editor-date timezone logic

packages/rich-text/src/prepareDocument.ts
=> chore: [] Check content for undefined

packages/rich-text/package.json, packages/rich-text/src/plugins/Marks/Subscript.tsx, packages/rich-text/src/plugins/Marks/Superscript.tsx, yarn.lock
Explicitly setting superscript and subscript styles as running into issues with consumers normalising the styles
=> fix: explicitly setting sub super styles [TOL-30]

packages/reference/src/resources/useResourceLinkActions.ts
Falling back to generating urn when one does not exist on the entity, this was causing the resource editor to not display the xspace references.
=> chore: adding fallback when urn not in resource link [ZEND-3052]

packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.tsx, packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
- Display the search when there are 5+ options in the add content dropdown
- Make the dropdown have a reasonable `max-width`: from 240px to 300px
=> feat: lower search and update width entry ref [TOL-247]

cypress/integration/rich-text/RichTextEditor.spec.ts, cypress/support/index.d.ts, cypress/support/index.js
Add a test for keyboard navigation for rich text editor
Follow-up for https://github.com/contentful/field-editors/pull/1315
=> test: rich text keyboard navigation [TOL-141]

.circleci/config.yml
- Removes hardcoded ssh fingerprint
- Uses new `vault` context to get the necessary keys
=> ci: update circleci config to use vault []

packages/reference/src/resources/MultipleResourceReferenceEditor.spec.tsx
Tests are flaky, myself and @giotiskl felt like they were doing too much. Separating into smaller tests
=> chore: fixing flaky test [TOL-854]

cypress/integration/rich-text/RichTextEditor.spec.ts, packages/rich-text/src/plugins/CommandPalette/useCommands.ts, packages/rich-text/src/plugins/index.ts, packages/rich-text/src/test-utils/createEditor.ts
Only enable the command palette plugin if at least one action type is allowed
https://contentful.atlassian.net/browse/TOL-960
=> fix(rte): [TOL-960] conditional command palette plugin enablement

.circleci/config.yml, .contentful/vault-secrets.yaml
=> feat: migrate Field editors to use NPM_TOKEN from vault [TOL-938]

packages/date/src/DateEditor.tsx
Allow date component to be disabled through passing a prop
=> feat: support disabling dateField []

packages/location/package.json, packages/location/src/GoogleMapView.tsx, packages/location/src/LocationEditor.tsx, packages/location/src/LocationSearchInput.tsx, packages/location/src/LocationSelector.tsx, packages/location/src/types.ts, yarn.lock
update google-maps-react package & types
=> feat: upgrade google-maps-react [TOL-968]

packages/date/src/DateEditor.tsx
Clean up to make use of the new `isDisabled` logic in the `FieldConnector`.
=> fix: pass isDisabled into FieldConnector

packages/rich-text/src/plugins/PasteHTML/utils/sanitizeHTML.ts
Moving from RegEx to document speeds up the removal of div wrappers around tables and therefor it won't crash anymore on larger documents.
With the plate update to v20 we can remove the workaround anyways as it is then fixed directly inside plate.
https://contentful.atlassian.net/browse/TOL-1092
=> fix(RTE): copy-paste perf issues on larger documents

apps/rich-text-app/package.json, apps/rich-text-app/src/index.tsx, apps/rich-text-app/tsconfig.json, package.json
Currently the rich-text-app cannot be started, update dependencies to get it working again on the short term.
For the long term it needs some more magic to be working well again. (Follow up ticket)
=> chore(rich-text-app): update dependencies to be startable again []

packages/rich-text/src/plugins/Marks/InlineComment.tsx, packages/rich-text/src/plugins/Marks/index.ts
=> feat: add inline-comment renderer

packages/rich-text/src/RichTextEditor.styles.ts, packages/rich-text/src/RichTextEditor.tsx
https://github.com/contentful/field-editors/assets/30434146/dff0d32c-94c7-46c8-877e-25f086eab97f
=> feat: add max height property to rich text editor [SPA-1200]

packages/default-field-editors/jest.config.js, packages/markdown/package.json, packages/markdown/src/MarkdownEditor.tsx, packages/markdown/src/components/MarkdownPreview.tsx, packages/markdown/src/components/MarkdownPreviewSkeleton.tsx, packages/markdown/src/dialogs/ZenModeModalDialog.tsx, packages/markdown/src/index.tsx, yarn.lock
- Replace markdown-to-jsx with react-markdown 
- Lazily load the package when needed (lazy loading the preview tab)
=> feat: switch to react-markdown, lazy loading [TOL-501]

packages/_shared/src/FieldConnector.test.tsx, packages/_shared/src/FieldConnector.ts, packages/boolean/src/BooleanEditor.tsx, packages/checkbox/src/CheckboxEditor.tsx, packages/date/src/DateEditor.tsx, packages/dropdown/src/DropdownEditor.tsx, packages/list/src/ListEditor.spec.tsx, packages/list/src/ListEditor.tsx, packages/markdown/src/MarkdownEditor.tsx, packages/radio/src/RadioEditor.tsx, packages/rating/src/RatingEditor.tsx, packages/reference/src/common/ReferenceEditor.tsx, packages/reference/src/resources/MultipleResourceReferenceEditor.tsx, packages/reference/src/resources/SingleResourceReferenceEditor.tsx, packages/rich-text/src/RichTextEditor.tsx, packages/slug/src/SlugEditor.tsx, packages/tags/src/TagsEditorContainer.tsx
Replacing throttling logic with debounce to prevent laggy updates of state inside of input fields.
=> feat: [TOL-1405] Replace throttling with debounce in field editors

packages/markdown/package.json, packages/markdown/src/MarkdownEditor.tsx, packages/markdown/src/components/MarkdownBottomBar.tsx, packages/markdown/src/components/MarkdownPreview.tsx, packages/markdown/src/components/MarkdownToolbar.tsx, packages/markdown/src/dialogs/ZenModeModalDialog.tsx, packages/markdown/src/dialogs/renderMarkdownDialog.tsx, yarn.lock
- introduce markdown sanitize helper info text
- change sanitization plugin to rehype sanitize
- refactor the full page markdown modal. It was broken in production. I used CSS grid instead of fixed positions.
- fix tooltip not showing anymore in header
Ticket: https://contentful.atlassian.net/browse/TOL-497
=> feat: markdown sanitize changes [TOL-497]

cypress/e2e/rich-text/RichTextEditor.Links.spec.ts, cypress/fixtures/utils.ts, packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx, yarn.lock
Autofocus the correct input fields when adding a link to rich text
https://contentful.atlassian.net/browse/TOL-1502
=> feat: set focus in link modal [TOL-1502]

packages/rich-text/src/plugins/Hyperlink/components/styles.ts
Fixing broken hyperlink display due to https://github.com/contentful/forma-36/commit/a331cc1aff7ee44b54f40d849cc320f61031432e
=> fix: fixing broken hyperlink display []

package.json, packages/reference/src/components/SpaceName/SpaceName.tsx, yarn.lock
Update f36 components to have updated card styles in reference
=> chore: update f36 components [TOL-1721]

packages/rich-text/src/plugins/Table/onKeyDownTable.ts
Fixing sentry issue: https://contentful.sentry.io/issues/4228755520/?project=8049&query=is%3Aunresolved+assigned%3A%23team-tolkien&referrer=issue-stream&statsPeriod=90d&stream_index=0
=> fix: cannot read properties of null (reading 'attributes') []

packages/reference/src/index.tsx, packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx, packages/reference/src/resources/index.ts, packages/reference/stories/ExternalReferenceCard.stories.tsx
Creating a new card for external resources
=> feat: create card component for external resources [DANTE-1330]

.circleci/config.yml, .npmrc
Deleting .npmrc to fix release step
=> fix: removing .npmrc to fix release step []

.gitignore, .prettierignore, lerna.json, nx.json, package.json, yarn.lock
upgrading to latest version
v8 changes: https://github.com/lerna/lerna/releases/tag/v8.0.0
v7 changes: https://github.com/lerna/lerna/releases/tag/7.0.0
=> chore: upgrade lerna to latest []

packages/reference/src/common/EntityStore.tsx, packages/reference/src/index.tsx, packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
follow up on https://github.com/contentful/field-editors/pull/1641
=> refactor(rich-text): better handling for status []

cypress/component/rich-text/RichTextEditor.Tracking.spec.ts, packages/rich-text/src/Toolbar/components/ButtonRedo.tsx, packages/rich-text/src/Toolbar/components/ButtonUndo.tsx, packages/rich-text/src/internal/types/editor.ts, packages/rich-text/src/plugins/Tracking/createTrackingPlugin.ts
Add tracking for undo and redo buttons
- via toolbar
- via shortcut
=> feat: undo redo rich text tracking [TOL-1987]

packages/_shared/src/FieldConnector.ts
We implemented an unwanted breaking change, without announcing it.
This PR restores the property as a fallback and deprecates it for future removal
=> fix(FieldConnector): restore 'throttle' property []

cypress/component/reference/MultipleEntryReferenceEditor.spec.tsx, packages/_shared/src/utils/entityHelpers.ts
Allows us to bump all field editor packages again
=> fix(shared): disable fieldStatus handling temporary [TOL-2143]

packages/markdown/package.json, packages/reference/package.json, packages/rich-text/package.json, yarn.lock
- bump constate and don't pin it
fixes https://github.com/contentful/field-editors/issues/1631
=> chore(dependencies): maintenance

package.json, packages/rich-text/package.json, yarn.lock
Updating rich text types to support ol & ul list in table cells
=> chore: upgrade rich text type [TOL-2249]

packages/rich-text/README.md, packages/rich-text/src/internal/types/editor.ts
fixes https://github.com/contentful/field-editors/issues/1698
=> chore(rich-text): update url for plate []

apps/singleline-app/package.json, package.json, packages/_shared/package.json, packages/_test/package.json, packages/default-field-editors/package.json, packages/dropdown/package.json, packages/markdown/package.json, packages/radio/package.json, packages/reference/package.json, packages/reference/src/common/EntityStore.tsx, packages/reference/src/resources/Cards/ResourceCard.spec.tsx, packages/rich-text/package.json, packages/slug/package.json, yarn.lock
We want to have all available resource types in memory hence we fetch all available pages. Depends on https://github.com/contentful/contentful-management.js/pull/2365.
=> feat: 🎸 fetch all resource types

packages/rich-text/package.json, yarn.lock
editor still working as expected including embedding references
=> feat: upgrade slate [TOL-2368][TOL-2389]

packages/json/src/JsonEditor.tsx, packages/rich-text/src/RichTextEditor.tsx
Closes https://github.com/contentful/field-editors/issues/1236
=> fix: broken rich text onChange prop

packages/reference/src/components/ScheduledIconWithTooltip/ScheduledIconWithTooltip.tsx, packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
closes https://github.com/contentful/field-editors/issues/454
=> fix(reference): set state after unmount []

packages/_shared/src/LocalePublishingEntityStatusBadge/LocalePublishingPopover.tsx, packages/_shared/src/LocalePublishingEntityStatusBadge/LocalePublishingStatusList.tsx, packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx, packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx, packages/reference/src/common/customCardTypes.ts, packages/reference/src/components/EntityStatusBadge/EntityStatusBadge.tsx, packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Simplify dependencies while still allowing for requesting more attributes in future.
=> feat: declare explicit locale attrs dependency

packages/_shared/src/utils/entityHelpers.test.ts, packages/_shared/src/utils/entityHelpers.ts, packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx, packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx, packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx, packages/reference/src/common/customCardTypes.ts, packages/reference/src/components/EntityStatusBadge/EntityStatusBadge.tsx, packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx, packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx, packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
This PR reverts https://github.com/contentful/field-editors/pull/1796
=> chore: revert show stacked badge when status diff []

packages/_shared/src/LocalePublishingEntityStatusBadge/LocalePublishingStatusList.tsx
=> fix: copy of status popover [TOL-2555]

packages/_shared/src/LocalePublishingEntityStatusBadge/LocalePublishingStatus.tsx
Rename default copy in locale popover
=> fix: default rename copy [TOL-2555]

packages/date/src/DatepickerInput.tsx
In a follow up we will consider respecting the content model validation settings
=> feat(date): allow arbitrary date range [ZEND-5700]

.eslintrc.js, packages/single-line/src/SingleLineEditor.tsx
Remove an unintentional console message and add an eslint warning about console messages.
```txt
field-editors git:(single-line-editor/remove-console-log) ✗ 🌺 git status
On branch single-line-editor/remove-console-log
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
modified:   packages/single-line/src/SingleLineEditor.tsx
field-editors git:(single-line-editor/remove-console-log) ✗ 🌺 git diff --cached
diff --git a/packages/single-line/src/SingleLineEditor.tsx b/packages/single-line/src/SingleLineEditor.tsx
index 3445a2c8..b180a5c6 100644
--- a/packages/single-line/src/SingleLineEditor.tsx
+++ b/packages/single-line/src/SingleLineEditor.tsx
export function SingleLineEditor(props: SingleLineEditorProps) {
+  console.log(`props => `, props);
field-editors …
```
=> style: remove console message [LUMOS-312]

packages/validation-errors/src/ValidationErrors.tsx
Allow to override error messaging with callback.
=> feat: [TOL-2595] Allow overriding error messages

baseJestConfig.js, cypress.config.ts, cypress/support/component.ts, jest.setup.js, package.json, packages/_shared/src/PredefinedValuesError.tsx, packages/checkbox/src/CheckboxEditor.tsx, packages/dropdown/src/DropdownEditor.tsx, packages/json/src/JsonInvalidStatus.tsx, packages/markdown/src/dialogs/EmdebExternalContentDialog.tsx, packages/radio/src/RadioEditor.tsx, packages/reference/src/components/LinkActions/LinkActions.tsx, packages/reference/src/components/LinkActions/NoLinkPermissionsInfo.tsx, packages/reference/src/components/MissingEntityCard/MissingEntityCard.tsx, packages/reference/src/components/ResourceEntityErrorCard/FunctionInvocationErrorCard.tsx, packages/reference/src/components/ResourceEntityErrorCard/UnsupportedEntityCard.tsx, packages/rich-text/src/dialogs/HypelinkDialog/HyperlinkDialog.jsx, packages/slug/src/SlugEditorField.tsx, packages/tags/src/TagsEditorConstraints.tsx, packages/validation-errors/src/ValidationErrors.tsx, yarn.lock
Ticket: https://contentful.atlassian.net/browse/TOL-3263
=> chore: localize hardcoded strings [TOL-3263]

packages/_shared/src/types.ts
Add metadata types to shared release v2 types
=> feat: add release metadata types []

packages/_shared/package.json, packages/_shared/src/index.tsx, packages/_test/package.json, packages/boolean/package.json, packages/checkbox/package.json, packages/date/package.json, packages/default-field-editors/package.json, packages/dropdown/package.json, packages/json/package.json, packages/list/package.json, packages/location/package.json, packages/markdown/package.json, packages/multiple-line/package.json, packages/number/package.json, packages/radio/package.json, packages/rating/package.json, packages/rich-text/package.json, packages/single-line/package.json, packages/slug/package.json, packages/tags/package.json, packages/url/package.json, packages/validation-errors/package.json
Follow up to https://github.com/contentful/field-editors/pull/1923
Adding rest of the packages.
=> feat: [TOL-3355] Add esm modules export

packages/_shared/src/index.tsx
Fix import of the `File` type in shared package.
=> fix: [] File type import

README.md
Add i18n requirements documentation to README.
=> docs: [TOL-3355] Add section on i18n to README

packages/_shared/package.json, yarn.lock
Needed to resolve a type conflict in packages as part of TOL-3479
=> chore: bump contentful-management in shared package
