contentful/field-editors

- packages/slug/src/index.tsx
Expose makeSlug function for slugEditor, to be able to re-use the functionality of making slug out of a string with a fallback to default date-based slug
> refactor: [slug-editor] Expose makeSlug function

- packages/markdown/src/components/MarkdownTextarea/MarkdownTextarea.tsx
Properly fade the editor area and hide the blinking caret cursor.
> fix: add disabled state styles for the markdown field

- extensions/entry-extension-collapsible/src/Field.tsx
- extensions/markdown-extension/src/index.tsx
- extensions/multiple-references-extension/src/index.tsx
- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/SingleReferenceEditor.tsx
Renames `canCreateEntity` and `canLinkEntity` to `showCreateEntityAction` and `showLinkEntityAction` correspondingly.
1. After we introduced `sdk.access` methods the actual permissions check happens within field editors and these params control only visibility of the buttons.
2. We plan to expose these settings to be controlled from Appearance tab in the Web app.
> feat: rename reference initialization params

- .dependabot/config.yml
- .github/workflows/auto-approve.yml
To reduce a number of dependabot requests to approve
> ci: enable dependabot automerges

- extensions/entry-extension-collapsible/package.json
- extensions/markdown-extension/package.json
- extensions/multiple-references-extension/package.json
- extensions/rich-text-extension/package.json
- extensions/singleline-extension/package.json
- packages/_shared/package.json
- packages/_test/package.json
- packages/markdown/src/MarkdownEditor.mdx
- packages/markdown/src/dialogs/CheatsheetModalDialog.tsx
- packages/markdown/src/dialogs/ConfirmInsertAssetModalDialog.tsx
- packages/markdown/src/dialogs/EmdebExternalContentDialog.tsx
- packages/markdown/src/dialogs/InsertLinkModalDialog.tsx
- packages/markdown/src/dialogs/InsertTableModalDialog.tsx
- packages/markdown/src/dialogs/SpecialCharacterModalDialog.tsx
- packages/markdown/src/dialogs/ZenModeModalDialog.tsx
- packages/reference/package.json
- packages/rich-text/src/RichTextEditor.mdx
- packages/rich-text/src/dialogs/HypelinkDialog/HyperlinkDialog.jsx
- yarn.lock
The field editors throw an error if you open any form of a dialog from within an app. The method `openCurrent` handles this behaviour and decides if you should `openExtension` or `openCurrentApp`.
> fix: use dialogs.openCurrent to open dialogs

- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- yarn.lock
improves performance on rendering lots of links as we were doing `n^2` renderings of the link card where `n` is the number of links. We now do ~`n*2` renderings (one for loaded state, one for fetched link state)
> fix: 🐛 Improve link rendering performance

- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/rich-text/src/RichTextEditor.mdx
- packages/rich-text/src/plugins/EmbeddedEntityBlock/FetchingWrappedAssetCard.js
- packages/rich-text/src/plugins/EmbeddedEntityBlock/FetchingWrappedEntryCard.js
When clicking on reference cards within the rich text editor, the entry is immediately opened. This PR changes that so that clicking on a reference card only selects the card which allows the user to then press backspace to remove the referenced entry from the rich text editor field.
> fix: prevent rich text references from opening on click

- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
The `useEntities` hook used inside `FetchingWrappedEntryCard` and `FetchingWrappedAssetCard` provides the list of all entities `entries`/`assets` from the store and the `loadEntry`/`loadAsset` function. The problem is that each successful load call triggers a re-render of all components using the hook, even though we fetch all entities in one request because of optimization. So a list of 500 cards ends up being rendered 500^2 times before the page is fully loaded.
The recent fix https://github.com/contentful/field-editors/commit/f6e844dcd2f25ff5453d2ce6301ea021b5fcaca3 added `useMemo` inside `FetchingWrappedEntryCard` to re-render only when an entity changes. But it doesn't consider component props and introduced a few bugs, like card not updating after an edit or cards not switching to …
> fix(reference): optimize multiple references field rendering

- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
This PR allows embeds in the rich text editor to be draggable for purposes of moving within the rich text content, but will still prevent the embedded entry/asset cards from opening on click
> fix: allow draggable embeds in rich text

- packages/rich-text/src/RichTextEditor.jsx
- packages/rich-text/src/RichTextEditor.spec.js
- packages/rich-text/src/Toolbar/Toolbar.spec.js
- packages/rich-text/src/Toolbar/index.js
Moved async function to get asset access for the user into Tooltip
component, to avoid stale state
I looked into this bug (https://contentful.atlassian.net/browse/REACT-324) and it seems to me that state of the `RichTextEditor` component doesn't propagate to the `Toolbar` component on the first render of the `Toolbar` component. `setState` in `componentDidMount` didn't trigger re-render of the component. To avoid this, I moved this async function to `Toolbar`, as we provide the function needed anyway, and asset access seems to be related to the `Toolbar`.
I wasn't able to find an explanation for this reacts behaviour with un-updated props, so if anyone has any pointers, highly appreciated. 
✅ Closes: REACT-324
> fix: 🐛 (REACT-324) add asset button in rich text is unavailable

- packages/reference/src/assets/WrappedAssetCard/AssetCardActions.tsx
- packages/rich-text/src/Toolbar/StickyToolbarWrapper.js
Do not expose `opener` property when opening Media files in a new tab.
Also a small fix for the invalid `className` value in the other file.
https://contentful.atlassian.net/browse/PEN-1091
> fix: 🐛 Open media links without exposing window.opener

- packages/reference/src/common/EntityStore.ts
If `sdk.space.onEntityChanged` is available, use it to listen to entity changes and update them in the store instead of refreshing everything in `navigator.onSlideInNavigator`.
Currently `sdk.space.onEntityChanged` allows subscribing to changes per entity, so a set of listeners — for all entries and assets already loaded in the store — is instantiated in the hook.
> feat: 🎸 listen to pubsub entity updates in reference editor

- cypress/integration/MultipleReferenceEditor.spec.ts
- packages/reference/src/__fixtures__/FakeSdk.ts
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/SingleReferenceEditor.tsx
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
- packages/reference/src/entries/SingleEntryReferenceEditor.mdx
- packages/reference/src/entries/SingleEntryReferenceEditor.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/reference/src/index.tsx
- packages/reference/tsconfig.json
- packages/rich-text/src/plugins/EmbeddedEntityBlock/FetchingWrappedEntryCard.js
Adds a `renderCard: (props: CustomEntryCardProps) => React.ReactElement | false;` prop to reference editors.
Closes https://github.com/contentful/field-editors/issues/283
> feat: Reference editor custom card render prop

- packages/reference/src/assets/MultipleMediaEditor.tsx
- packages/reference/src/assets/SingleMediaEditor.tsx
The `renderCustomCard` is not yet implemented for media (asset link) editors thus, it should be removed from their list of props and documentation.
> fix: Remove renderCustomCard prop from media editors

- packages/rich-text/src/plugins/shared/MarkPlugin.js
In an enviornment with reset css styles code and italic marks might have shown as normal text. This change ensures they are formatted explicitly.
> fix: 🐛 ensure correct style for code and italic marks

- packages/reference/src/assets/MultipleMediaEditor.tsx
- packages/reference/src/assets/SingleMediaEditor.tsx
- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/SingleReferenceEditor.tsx
- packages/reference/src/entries/SingleEntryReferenceEditor.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
This PR adds an `hasCardEditActions ` prop to the Reference Editor. This prop defaults to true but when set to false it will hide the edit option from the CardActionMenu.
> feat: add hascardeditactions flag to reference editor

- packages/rich-text/src/Toolbar/index.js
- packages/rich-text/src/plugins/EmbeddedEntityBlock/ToolbarIcon.js
- packages/rich-text/src/plugins/EmbeddedEntryInline/ToolbarIcon.js
- packages/rich-text/src/plugins/Hyperlink/ToolbarIcon.js
- packages/rich-text/src/plugins/List/ToolbarDecorator.js
- packages/rich-text/src/plugins/shared/BlockSelectDecorator.js
- packages/rich-text/src/plugins/shared/BlockToggleDecorator.js
- packages/rich-text/src/plugins/shared/MarkToggleDecorator.js
- packages/rich-text/src/plugins/shared/PluginApi.js
- packages/rich-text/src/plugins/shared/Util.js
When the user clicks on a Rich Text editor toolbar action while the
editor is not focused, this should ideally result in focusing the editor
and applying the clicked action.
This handling has been implemented for some actions and it has been
breaking in some cases. This change introduces consistent handling and
dealing with Slate related limitations.
The main limitaton would be after initializing Rich Text, before the
user has manually focused the rich text field, we can not set the focus
programmatically as the Slate internal value seems to lack some
properties that can result in a crash at this point. We circumvent bugs
by preventing any action when clicking on a toolbar action. Instead, the
user has to focus the input first. This is pretty much consistent with
the previous behavior but …
> feat: 🎸 refined editor focusing when using toolbar actions

- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
This PR fixes an issue where cards were rendered as not clickable (clicking the card did not perform the open slide-in editor action)
> fix(reference-editor): fix isclickable prop

- packages/checkbox/src/CheckboxEditor.spec.tsx
- packages/checkbox/src/CheckboxEditor.tsx
- packages/checkbox/src/styles.ts
When a predefined checked checkbox value is invalid and page is reloaded, the value disappears which makes it impossible for users to unselect or remove invalid value.
This PR makes it possible for the user to see the invalid value and be able to remove it.
> fix: users should be able to remove checkbox with invalid predefined values

- packages/rich-text/src/plugins/shared/MarkPlugin.js
Fixes the following unpleasant effect whenever applying a code mark (also applies for normal text, not just headings)
> fix: 🐛 vertical jitter effect when applying rich text code mark

- packages/rich-text/src/dialogs/HypelinkDialog/HyperlinkDialog.jsx
- packages/rich-text/src/plugins/Hyperlink/Util.js
Implements more sensible auto focus behavior for rich text url modal dialog inputs instead of always auto focusing the url.
Cases when opening dialog:
- When displaying only url input: Focus url
- When displaying both link text (not empty) and url inputs: Focus url
- When displaying both link text (empty) and url inputs: Focus text
- When displaying another link type (theoretical case): Focus text
Also fixes the modal's input auto focusing in some cases by accounting for Slate editor input bluring efore opening the url dialog.  Without this, focus would stay with Slate, even while the modal is open, until the user clicks on a modal input. This also means if the user were to write while the modal is open before clicking on an input, the text would be added in the background to the editor, …
> feat: improve rich text url input auto focus

- packages/validation-errors/src/ValidationErrors.tsx
To be able to consume in downstream dependencies.
> chore: 🤖 use proper testId for validation errors components

- packages/markdown/src/MarkdownEditor.tsx
Writing MDX (and MD with html tags) in the markdown editor can lead to a bad experience for editors, ultimately breaking their (Gatsby) website while the developer is absent.
This is due to limitations of MDX (and maybe some other MD renderers as well).
MDX (v1) requires you to have an empty line between MDX and MD sections.
Unfortunately, it is very easy to accidentally add whitespace to empty lines when using MDX. It happens unintentional when writing tags with child tags.
CodeMirror indents the HTML tag automatically, but does not un-indent when you write the closing tag.
If you are not careful when writing MDX, you leave a empty line with a few white spaces.
Check the white space within the `<div/>` and the line after. This breaks the MDX renderer.
```
with a paragraph below
<div> …
```
> fix: trim empty lines in markdown editor

- doczrc.js
- extensions/entry-extension-collapsible/src/Field.tsx
- packages/default-field-editors/README.md
- packages/default-field-editors/src/DefaultFieldEditors.mdx
- packages/default-field-editors/src/Field.tsx
- packages/default-field-editors/src/FieldWrapper.tsx
- packages/json/src/codemirrorImports.ts
Added documentation for `default-field-editors`. Fixed the styles import in `json`, so they are not imported by default breaking `docz`.
> chore: default field editors docs

- packages/rich-text/src/dialogs/HypelinkDialog/HyperlinkDialog.jsx
A small visual improvement for hyperlink modal dialog
> fix: 🐛 allow heigh overflow for hyperlink dialog [PEN-1218]

- packages/single-line/src/SingleLineEditor.test.tsx
- packages/single-line/src/SingleLineEditor.tsx
To be able to hide validations when it's not necessary, for example - asset editor.
> feat: 🎸 add withCharValidation property to hide validation

- packages/validation-errors/src/styles.ts
Vertically align the error message with the svg icon
> fix: center vertical align of error items

- packages/date/src/DateEditor.mdx
- packages/location/src/LocationEditor.mdx
- packages/markdown/src/MarkdownEditor.mdx
- packages/reference/src/assets/MultipleMediaEditor.mdx
- packages/reference/src/assets/SingleMediaEditor.mdx
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
- packages/reference/src/entries/SingleEntryReferenceEditor.mdx
Avoid `isInitiallyDisabled` being `null` due to getting it from `localStorage` where it may not be defined. This prevents annoying console warning stating that a boolean is expected in some components.
> fix: 🐛 isInitiallyDisabled being null in examples

- cypress/integration/MultipleMediaEditor.spec.ts
- packages/reference/src/assets/MultipleMediaEditor.mdx
- packages/reference/src/assets/SingleMediaEditor.mdx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.tsx
- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
- packages/reference/src/components/LinkActions/CombinedLinkActions.tsx
- packages/reference/src/components/LinkActions/LinkActions.tsx
- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
- packages/reference/src/components/LinkActions/styles.ts
- packages/reference/src/components/index.ts
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
- packages/reference/src/index.tsx
Introduces a new component `CombinedAssetLinkActions` that can be used in conjunction with reference and media editor `renderCustomCard` props. It introduces a new link actions layout which is planned to replace the current link actions in some future version of these editors.
**For references:**
**For assets:**
> feat: 🎸 introduce experimental CombinedAssetLinkActions

- cypress/integration/LocationEditor.spec.ts
- cypress/support/commands.js
- cypress/support/index.d.ts
Avoids repeating any lat/long so that flaky tests can more easily be fixed without replacing lots of values. Ideally though we would avoid relying on any actual web requests during tests and do contract testing instead.
> refactor: 💡 simplify location editor tests

- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/SingleReferenceEditor.tsx
- packages/reference/src/common/useEntityPermissions.ts
- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
- packages/reference/src/components/LinkActions/helpers.ts
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
Extracts props of `LinkEntityActions` to a hook `useLinkActionsProps`, so the same props can be passed to `renderCustomCard`.
Would allow to rendered custom card actions utilising `onCreate`, `onLinkExisting`, `availableContentTypes`.
> feat: 🎸 pass link actions props to a custom card renderer

- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/SingleReferenceEditor.tsx
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
- packages/reference/src/entries/SingleEntryReferenceEditor.mdx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/index.tsx
Created.  renderDefaultCard function and exposed to renderCustomCard to allow customization of props
This is needed for the new app to differentiate non flattened entries between pages and non pages
https://contentful.atlassian.net/browse/PEN-1190
> feat: 🎸 pass renderDefaultCard to renderCustomCard

- cypress/integration/MultipleMediaEditor.spec.ts
- cypress/integration/MultipleReferenceEditor.spec.ts
- cypress/support/commands.js
- cypress/support/index.d.ts
- packages/date/src/DateEditor.mdx
- packages/reference/src/__fixtures__/FakeSdk.ts
- packages/reference/src/assets/MultipleMediaEditor.mdx
- packages/reference/src/assets/SingleMediaEditor.mdx
- packages/reference/src/components/LinkActions/CombinedLinkActions.tsx
- packages/reference/src/components/LinkActions/LinkActions.tsx
- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
We do not want to show the link actions on a reference or media field which is already full (meaning the field has a max number of links validation and that number is met or exceeded). This is true for both the current editor link design as well as the experimental CombinedLinkActions design.
This is actually regarded as a regression, although one already in place for such a long while that we can probably treat it as a feature at this point (hence the `feat` commit).
This also removes a lot of redundant mocks used by the media field examples.
> feat: 🎸 do not show link actions on full reference/media fields

- packages/reference/src/components/LinkActions/CombinedLinkActions.tsx
- packages/reference/src/components/LinkActions/LinkActions.tsx
- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
When  there  are  assets  linked  on  a  media  field  using `CombinedLinkActions`, the link actions won’t be wrapped by the cards placeholder as it doesn’t go well with the asset cards which do not cover the full available horizontal space like the card placeholder.
:exclamation: This PR is based on and requires #437 to be merged first.
**Empty field:**
**Non-empty field (NEW):**
After this we can use `CombinedLinkActions` in the new app.
> feat: 🎸 hide CombinedLinkActions asset card on non‐empty field

- packages/reference/package.json
- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/components/LinkActions/LinkActions.tsx
- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
Adds support for inserting a new created or linked entity or entities at a given index in the `MultipleReferencesEditor`.
By default we're currently adding such entities to the end of the list. This PR allows the options for clients to insert wherever they'd like, e.g., immediately after the element in a list, depending on how the card's rendered.
Note this is non-breaking as the default behavior remains the same.
Also adds `@types/deep-equal` as my compiler was complaining about that.
> feat(reference-editor): insert at index

- packages/reference/src/components/LinkActions/redesignStyles.ts
This PR reduces the size of the combined link action empty state.
**Before**
**After**
> refactor(reference): resize combined link actions

- packages/reference/src/components/LinkActions/CombinedLinkActions.tsx
The new combined reference link action's dropdown will be positioned automatically, if necessary, above the trigger button (in most cases, if there's enough space, it will still be shown below). This should prevent the menu from being cut off when e.g. positioned at the end of a page.
> feat: 🎸 auto position combined link actions dropdown

- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
Closes  https://github.com/contentful/field-editors/issues/470
> fix: 🐛 use onAction for all remove actions (including missing)

- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
Now we have a stable behavior of the dropdown position and we can allow `create reference` dropdown to auto position itself.
> chore: 🤖 enable autoalignment for default create reference button

- packages/reference/src/components/index.ts
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/index.tsx
Production build of docz is blocked because of warnings which are considered errors in CI. This PR unblocks it.
> chore: fix types imports to unblock docz production build

- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
- packages/reference/src/types.ts
This PR adds an `index` prop to the `select_and_link` and `create_and_link` action types.
> feat(link-actions): add reference index to action props

- packages/boolean/src/Boolean.spec.tsx
- packages/boolean/src/BooleanEditor.tsx
"Clear" button shouldn't be clickable if the field is disabled
> fix: clear button should respect disabled state

- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
Next steps:
- bump the dependency in the web app
- bump the dependency in entity selector
Here I did the same thing we do already for entry references
> feat(asset reference): add support for scheduled icon [PUL-1206]

- packages/reference/src/common/useEditorPermissions.spec.ts
- packages/reference/src/common/useEditorPermissions.ts
The check for permissions on read entity are too pessimistic.
There are situation where we can have enitites to reference, but we don't offer the "select content to link" button.
> feat(reference): adjust permissions

- packages/default-field-editors/src/Field.tsx
- packages/default-field-editors/src/getDefaultWidgetId.ts
- packages/default-field-editors/src/index.tsx
`widgetId` can be undefined, so we need to fallback to a default widgetId based on the information in content type
> feat: 🎸 fallback to a default inferred widget id

- packages/_shared/src/typesEntity.ts
- packages/_test/src/fakesFactory.ts
- packages/reference/src/common/useAccessApi.ts
- packages/reference/src/common/useEditorPermissions.spec.ts
- packages/reference/src/common/useEditorPermissions.ts
- yarn.lock
The access API is not working properly when we have permissions that have tags in them, the issue seems to be solved by  adding property `metadata.tags` to the dump entry generated in **makeEntryFromType**
> fix(tags): Editor permissions handles entities with metadata

- packages/reference/src/common/useAccessApi.ts
- packages/reference/src/common/useContentTypePermissions.ts
- packages/reference/src/common/useEditorPermissions.spec.ts
- packages/reference/src/common/useEditorPermissions.ts
The access check on content-types is slightly buggy in the web app and needs to be addressed separately.
> fix: 🐛 handle lack of proper acccess checks in the webapp

- packages/default-field-editors/README.md
- packages/default-field-editors/src/DefaultFieldEditors.mdx
- packages/default-field-editors/src/FieldWrapper.tsx
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
Added few more examples, explained the `widgetId` and made the `getEntryURL` prop optional.
> feat: default-field-editors doc improvements

- packages/reference/src/__fixtures__/FakeSdk.ts
- packages/reference/src/components/LinkActions/LinkActions.tsx
- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
This PR addresses https://github.com/contentful/field-editors/issues/586 by adding two callbacks to `LinkActionsProps`:
- `onCreated(entity: Entity, index?: number, slide?: NavigatorSlideInfo) => void`
- `onLinkedExisting(entities: Entity[], index?: number) => void`
These callbacks add a created/linked entry/entries to the reference field and can be used to implement custom creation/linking processes, for example duplicating an entry instead of creating a new empty one.
It can be achieved by rendering custom actions `renderCustomActions` and overriding `onCreate` and `onLinkExisting` properties of `CombinedLinkActions` (or creating completely new UI) and calling `onCreated` or `onLinkedExisting` to show the new items in the editor.
```js
<MultipleEntryReferenceEditor …
```
> feat: reference editor onCreated onLinkedExisting callbacks

- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/customCardTypes.ts
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/index.tsx
Allows the user to optionally render a custom missing entity reference card.
> feat: allow rendering of custom missing entity card

- .circleci/config.yml
- extensions/entry-extension-collapsible/.babelrc
- extensions/entry-extension-collapsible/package.json
- extensions/markdown-extension/.babelrc
- extensions/markdown-extension/package.json
- extensions/multiple-references-extension/.babelrc
- extensions/multiple-references-extension/package.json
- extensions/rich-text-extension/.babelrc
- extensions/rich-text-extension/package.json
- extensions/singleline-extension/.babelrc
- extensions/singleline-extension/package.json
- package.json
- packages/rich-text/.babelrc
- packages/rich-text/jest.config.js
- yarn.lock
The build process for the extensions / examples was broken since November due to a dependency update that included a forma version bump (https://github.com/contentful/field-editors/pull/467).  
The error resulted in a `Error: Duplicate plugin/preset detected.`
My approach was to remove duplicated `babel` dependencies that we already have declared in the root `package.json` file. I also added a build step that checks if the extensions are able to build.
> chore(extensions): fix build errors [EXT-2496]

- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/common/EntityStore.ts
- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
* Don't fetch new entries and assets when re-ordering elements (don't fetch if there's an item in the store already)
* Fix a few memorization problems by using statically defined variables (outside of react components)
* Loading thumbnail for entry preview also set an image to the store
> feat(reference): performance optimizations

- cypress/integration/MarkdownEditorVoidElements.spec.ts
- packages/markdown/package.json
- packages/markdown/src/MarkdownEditor.tsx
- packages/markdown/src/components/MarkdownPreview/MarkdownPreview.tsx
- packages/markdown/src/components/VoidElements/VoidElements.tsx
- packages/markdown/src/components/VoidElements/VoidElementsWarning.tsx
- packages/markdown/src/components/VoidElements/index.ts
- packages/markdown/src/components/VoidElements/useVoidElements.ts
- yarn.lock
Usage of void elements in the markdown crashes the preview because React won't let us render children for those elements. We hereby surface that problem to the user in order to give them a way out of that otherwise dead end.
> feat: gracefully handle void elements

- packages/default-field-editors/src/Field.spec.tsx
- packages/default-field-editors/src/Field.tsx
Changing locales can sometimes cause the field editor of the previous locale to remain rendered in certain situations. This PR does some refactoring and adds a `key={sdk.field.locale}` to the rendered field editor component.
> fix(default-field-editors): re-render Field children on locale change

- cypress/integration/RichTextEditor.spec.ts
- packages/rich-text/src/plugins/Bold/index.tsx
- packages/rich-text/src/plugins/Code/index.tsx
- packages/rich-text/src/plugins/Italic/index.tsx
- packages/rich-text/src/plugins/List/index.tsx
- packages/rich-text/src/plugins/Underline/index.tsx
Tests for lists and toolbar mark buttons.
I had some issues when trying to test deeper lists, I couldn't add more than one item on the list.
To do that, I need to simular an `Enter` key press, so I've used `.type('{enter'})`, however, whenever I use this command, it breaks the next command and SlateJS.
The error is:
```
Cannot resolve a Slate node from DOM node: [object HTMLSpanElement]
``` 
I don't know if this a Cypress version bug, or how SlateJS detects events, we can try updating Cypress version to the latest if the problem is gone.
Any other idea?
EDIT:
Somebody told to intercalate some `.type('{enter}')` calls with some delays. I'm still testing this approach for lists.
> test: add tests for lists and toolbar mark buttons []

- packages/rich-text/src/plugins/List/index.tsx
Adds symbol styles for parity with the existing editor, most importantly `list-style: inherit` - without which client applications will not display _any_ list styles by default.
> feat: add symbol styles

- apps/entry-app-collapsible/package.json
- apps/markdown-app/package.json
- apps/multiple-references-app/package.json
- apps/rich-text-app/package.json
- apps/singleline-app/package.json
- packages/markdown/package.json
- packages/slug/package.json
- yarn.lock
Updated some dependencies, dedupes the yarn, so only `3.36.0` version of app SDK is used. Adds missing `app-sdk` dependency to `markdown` and `slug` editors
> chore: bump app-sdk to v3.36, add missing dependency

- packages/reference/src/assets/MultipleMediaEditor.mdx
- packages/reference/src/assets/SingleMediaEditor.mdx
- packages/reference/src/entries/MultipleEntryReferenceEditor.mdx
- packages/reference/src/entries/SingleEntryReferenceEditor.mdx
Fixes #741, previously we were using invalid reference editor instance parameters.
> chore: fix reference editor showCreateEntityAction/showLink params

- cypress/integration/RichTextEditor.spec.ts
- packages/rich-text/src/Toolbar/index.tsx
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/Quote/index.tsx
Disables the toolbar button and keyboard shortcuts for block element insertion within tables.
> feat: disable table block insertion

- packages/checkbox/src/CheckboxEditor.spec.tsx
- packages/checkbox/src/CheckboxEditor.tsx
Fixes non-unique labels of multiple checkbox editors, which was causing incorrect behavior when clicking on those labels.
> feat: fix non-unique checkbox labels for multiple editors

- cypress/integration/RichTextEditor.spec.ts
- packages/rich-text/src/RichTextEditor.mdx
- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/helpers/sanitizeSlateDoc.ts
- packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx
- packages/rich-text/src/plugins/Hyperlink/index.tsx
- packages/rich-text/src/types.ts
follows https://github.com/contentful/field-editors/pull/768
Allows editing hyperlinks, including changing a hyperlink to a different type of hyperlink (e.g. URL -> Entity and vice versa).
Plays well with tables
> feat: edit hyperlinks

- packages/rich-text/package.json
- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/helpers/deserializer.ts
- packages/rich-text/src/plugins/Bold/index.tsx
- packages/rich-text/src/plugins/Code/index.tsx
- packages/rich-text/src/plugins/Italic/index.tsx
- packages/rich-text/src/plugins/Underline/index.tsx
- yarn.lock
~~**Cypress tests are coming.**~~
Cypress doesn't support really well copying & pasting so we decided to skip it. Unit tests were also taken into consideration but we decided not to do it as well because we would be testing SlateJS functions only.
**Google Docs**
**Result**
> feat: add serializer plugin for marks

- .circleci/config.yml
- lerna.json
- packages/rich-text/package.json
Auto publishes packages in the `next` branch just like in master with a few exceptions:
* Packages should be published with `next` tag
* Github Releases should be marked as `prerelease`
> chore: auto publish alpha Rich Text package

- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Affects the `WrappedEntryCard` element of the reference editor
> feat: add hasMoveOptions property

- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Fixes https://github.com/contentful/field-editors/pull/784
For reasons not obvious to me, `false` actually causes this to fail with
```
TypeError: Cannot read property 'type' of null
```
I confess I am not sure why this solution works (ternary to default `undefined` or anything else falsy has the same problem), but it's low cost and accomplishes basically the same thing with the same DOM markup in the end. If anyone has any further suggestions / thoughts, I am open.
> fix: render dropdown list or fragment

- cypress/integration/RichTextEditor.spec.ts
- packages/rich-text/package.json
- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/Toolbar/index.tsx
- packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx
- packages/rich-text/src/plugins/EmbeddedEntityBlock/index.tsx
- packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx
- packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
- yarn.lock
- keyboard shortcuts
- cypress tests
Also
> feat: add embedded entity inline

- apps/entry-app-collapsible/package.json
- apps/markdown-app/package.json
- apps/multiple-references-app/package.json
- apps/rich-text-app/package.json
- apps/singleline-app/package.json
- package.json
- packages/boolean/package.json
- packages/checkbox/package.json
- packages/date/package.json
- packages/default-field-editors/package.json
- packages/dropdown/package.json
- packages/json/package.json
- packages/list/package.json
- packages/location/package.json
- packages/markdown/package.json
- packages/multiple-line/package.json
- packages/number/package.json
- packages/radio/package.json
- packages/rating/package.json
- packages/reference/package.json
- packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.spec.tsx
- packages/rich-text/package.json
- packages/single-line/package.json
- packages/slug/package.json
- packages/tags/package.json
- packages/url/package.json
- packages/validation-errors/package.json
- yarn.lock
This PR enables back the test we disabled for color tokens migration. Now the forma-36 package is updated and doesn't cause tests to fail with a type error.
> test: 💍 Enable back the "CreateEntryLinkButton" test

- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Reverts part of #784 
Only:
- doesn't impose `event.preventDefault()` on click events when the element is not clickable
This is making the embedded blocks being clickable on the rich text field.
A better solution should be made, for example, I think we don't need the `isClickable` at all, we can simply not pass the `entryUrl` or `getAssetUrl` property, but more time to test would be needed for this change.
> fix: revert prevent default

- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
Fix issue with the search inside the dropdown losing focus after each change.
> fix: 🐛 search on dropdown losing focus after change

- packages/rich-text/src/plugins/EmbeddedEntityBlock/Util.ts
Fixes block embed insertion in the webapp (or in other embedded contexts).
It's possible for the `selection` to get lost in these contexts when, e.g., selecting an entity means prompting a modal (and selecting from that modal using the mouse). To address this, we capture the selection before reaching `selectEntity` and reset the selection with `Transforms.select` right afterward.
> fix: block embeds

- packages/slug/package.json
- packages/slug/src/SlugEditor.test.tsx
- packages/slug/src/SlugEditor.tsx
- packages/slug/src/SlugEditorField.tsx
- yarn.lock
Introduce debounced logic (1000 ms) for firing requests to check for field uniqueness.
It should significantly decrease the number of requests to `entries` endpoint.
Optimized callbacks by wrapping them in React.useCallback and providing with a correct set of dependencies.
> feat: throttle slug editor uniqueness requests

- packages/_shared/package.json
- packages/_shared/src/FieldConnector.test.tsx
- packages/_shared/src/FieldConnector.ts
The `FieldConnector` currently only works correctly when the `onValueChanged` is triggered immediately after calling `setValue`. If another callback triggers a rerender (e.g. `onSchemaErrorsChanged`) the child component is rerendered with an outdated `value`. This can be potentially caused by `setValue` triggering a longer async function (e.g. a network connection). This gives plenty of time for another callback to fire. Also, throttling the `setValue` may also cause race conditions here.
This PR resolves this problem by immediately storing the value of `setValue` in the `FieldConnector`'s state. That way all future rerenders triggered by any callback will always pass the correct value to the component's `children`. The `setValue` call of the `FieldAPI` stays throttled to not break any …
> fix: FieldConnector setValue race conditions

- packages/rich-text/package.json
- yarn.lock
Bumps `slate`, `slate-react` and `slate-history` to the latest versions. 
Was originally done as part of #807 but that won't be merged soon.
> chore(dep): upgrade slate packages []

- packages/rich-text/package.json
> chore(rich-text): bump @contentful/field-editor-rich-text to 0.21.6-next

- apps/rich-text-app/package.json
- packages/default-field-editors/package.json
Ensures all packages in the mono repo reference the `next` branch's `@contentful/field-editor-rich-text` version to avoid pulling in the old RT version which seems like it can cause issues.
> chore: update dependencies on RT by other packages

- packages/rich-text/src/Toolbar/EmbedEntityWidget.tsx
Fixes a small UI issue when:
* Embed entity dropdown is open and
* The user focuses in and out of a table
* The dropdown will open and close
The fix is to force close the dropdown when we switch to a single button layout.
> fix(rich-text): embed entity widget dropdown glitch

- packages/rich-text/src/plugins/EmbeddedEntityInline/Util.ts
- packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx
Ensures when inserting inline embeds, after calling focus stealing entity picker, the embed is inserted at the original text selection.
> fix(rich-text): correct inline embeds insertion

- packages/rich-text/src/helpers/editor.ts
A partial fix for toggling blockquotes inside list elements. It's partial because it won't create a blockquote item but at list it won't break the list.
> fix(rich-text): keep lists when toggling blockquotes

- cypress/integration/RichTextEditor.spec.ts
- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/InsertBeforeFirstVoidBlock/index.tsx
It works for:
- HR
- Embedded asset
- Embedded entry
Any other void block?
> chore: create insert before first void block global plugin

- packages/rich-text/package.json
- packages/rich-text/src/plugins/InsertBeforeFirstVoidBlock/index.tsx
- yarn.lock
Using one of their solutions to replace `setTimeout`. We decided to use their own plugin. The whole conversation can be read here: https://slate-js.slack.com/archives/C013QHXSCG1/p1631208644108100?thread_ts=1631022429.081900&cid=C013QHXSCG1
The second solution would be just adding a `select: true` property to `Transforms.insertNodes` such as:
```
Transforms.insertNodes(editor, paragraph, { at: currentPath as Path, select: true }
```
> refactor: use exit break plugin instead

- cypress/integration/LocationEditor.spec.ts
- packages/_shared/src/index.tsx
- packages/_shared/src/utils/isValidImage.ts
Next step: remove this util from the `reference` package and bump a minor version there, so current packages using it won't break.
> feat: export shared util to validate images

- packages/rich-text/package.json
- yarn.lock
The actual fix is done by the Slate team in `v0.66.0`
>  fix(rich-text): corrupted tables on paste

- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/plugins/Paste/index.tsx
- packages/rich-text/src/plugins/Paste/sanitizers/helpers.tsx
- packages/rich-text/src/plugins/Paste/sanitizers/index.tsx
- packages/rich-text/src/plugins/Paste/sanitizers/removeComments.tsx
- packages/rich-text/src/plugins/Paste/sanitizers/sanitizeTables.tsx
Fixes a couple of issues caused by the paste buffer being overly permissive in respect to HTML elements.
> fix: paste issues

- cypress/integration/RichTextEditor.spec.ts
- packages/rich-text/package.json
- packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx
- packages/rich-text/src/plugins/shared/EntityStatusIcon.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
- yarn.lock
It fixes and re-implement entry and asset cards. It mimics some of the behavior from the `referece` package but I removed all the unnecessary parts for the `rich-text`.
> refactor: implement entry card for rich text

- apps/entry-app-collapsible/src/CollapsibleFieldGroup.tsx
- apps/entry-app-collapsible/src/FieldGroupsEditor.tsx
- packages/default-field-editors/package.json
- packages/default-field-editors/src/DefaultFieldEditors.mdx
- packages/default-field-editors/src/FieldWrapper.tsx
- packages/markdown/src/dialogs/EmdebExternalContentDialog.tsx
I'm not sure if it's 100% correct decision to refactor the `HelpText` to simple `Text` in the places where it's actually used in pair with form fields. But from other side using `FormControl.HelpText` without `FormControl` itself will bring even more confusion. 🤷‍♂️ 
For example `FieldWrapper` component seems like a bit customised `FormControl` component from our forma36 components.
> refactor: refactor HelpText to Text from Forma36 v4 [BAU-104]

- packages/rich-text/src/plugins/Table/index.tsx
Adds `hasHeadersOutsideFirstRow: boolean` as a property to the table paste tracking event to track instances in which tables with header cells outside the first row are pasted into the editor.
This comes with the usual caveat for table pasting events, which is that we do not capturing instances in which tables previously existed in the editor. This is for simplicity and performance's sake, and should not impede capturing a roughly equivalent percentage of "headers outside first row" occurrences _as a % of table paste events as a whole.
> feat: track tables with headers outside first row

- packages/rich-text/src/ContentfulEditorProvider.ts
- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/plugins/Bold/index.tsx
- packages/rich-text/src/plugins/Code/index.tsx
- packages/rich-text/src/plugins/EmbeddedEntityBlock/ToolbarIcon.tsx
- packages/rich-text/src/plugins/EmbeddedEntityBlock/index.tsx
- packages/rich-text/src/plugins/Heading/index.tsx
- packages/rich-text/src/plugins/Hr/index.tsx
- packages/rich-text/src/plugins/Hyperlink/index.tsx
- packages/rich-text/src/plugins/Italic/index.tsx
- packages/rich-text/src/plugins/List/index.tsx
- packages/rich-text/src/plugins/Quote/index.tsx
- packages/rich-text/src/plugins/Table/index.tsx
- packages/rich-text/src/plugins/Underline/index.tsx
It seems [`EditorToolbarButton`](https://github.com/contentful/forma-36/blob/master/packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarButton/EditorToolbarButton.tsx#L56) accepts `onMouseDown`, just its TypeScript is not configured correctly. 
On the other hand, [`DropdownListItem`](https://github.com/contentful/forma-36/blob/master/packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx#L62) also accepts `onMouseDown` but its TypeScript has correct types.
> fix: safari lost of editor selection

- packages/rich-text/src/plugins/Paste/sanitizers/sanitizeTables.tsx
- packages/rich-text/src/plugins/Table/index.tsx
Accomplishes this in the `normalizeNode` step definition for tables.
If an incoming child node is invalid, we:
- convert it to a contentful node
- gets the plain text value of the contentful node, as we would we with a document (using `@contentful/rich-text-plain-text-renderer`
- renders the plain text value inside a paragraph in place of the invalid node
This works well with insertion in empty table cells as well as within text selections from table cells.
> fix: render invalid table children as text

- packages/reference/src/common/EntityStore.ts
- packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
In our revised rich text entity card wrapper components we assume, wrongly, that an entity retrieved from the reference editor's `useEntities` constate will always be either an entity accessor API or `undefined`. Actually there's a third option: [`failed`](https://github.com/contentful/field-editors/blob/7e5940b963add53a73a1257221ce16e7e17cd49c/packages/reference/src/common/EntityStore.ts#L5-L11), which _should_ appear in our typespecs. But for whatever reason `useEntities` is appearing in my vscode as `any`.
So this PR addresses two defects:
- Cases in which an entry is `failed` are handled, and treated as though the entry object were `undefined`.
- A `TODO` is added to the reference editor's `EntityStore` to deal with the `constate` typing.
On that last point: ideally we'd also be …
> fix: handle 'failed' entity state

- apps/rich-text-app/package.json
- packages/default-field-editors/package.json
- packages/rich-text/package.json
It contains fixes for:
- Embedded asset details
> chore: bump rte next to 0.26.4-next

- packages/rich-text/package.json
- yarn.lock
`@contentful/rich-text-plain-text-renderer` is used in https://github.com/contentful/field-editors/blob/b161fd6fbec9c91ffbcb4fd0335f311d1ce753b5/packages/rich-text/src/plugins/Table/index.tsx#L16 but is not a dependency.
Without that dependency, the field editor cannot be used without also manually installing `@contentful/rich-text-plain-text-renderer`.
I am not sure whether 15.0.0 is the right version to go for here, but I guess it should be fine? ¯\_(ツ)_/¯
> fix: add rich-text-plain-text-renderer as rich-text dep

- packages/default-field-editors/src/FieldWrapper.tsx
Use sdk.field information to pass a unique field id
> fix: pass a unique form-control id

- package.json
- yarn.lock
Yarn auto resolved lockfile conflicts for 1c829c9 merge instead of
b76456f lockfile.
Shouldn't make a big difference but not sure how the b76456f lockfile
came to be.
> chore: auto resolved lock file

- packages/rich-text/src/Toolbar/EmbedEntityWidget.tsx
Disable inline entry in embedding dropdown.
The `next` logic was missing a similar check to `canInsertInline` [here](https://github.com/contentful/field-editors/blob/526bde6e10e0ee3789705ec10fb31489af7ca59e/packages/rich-text/src/plugins/EmbeddedEntryInline/ToolbarIcon.js#L47).
The old logic seems more generic that the one used in this PR, but I didn't find an easy way to do the same operations with the new editor object.
> fix: forbid embed entries in links

- package.json
- packages/rich-text/package.json
- yarn.lock
This also updates the contentful-slate-adapter to ensure contentful RT nodes with empty `content: []` will get an empty text leaf in their Slate representation so that the editor won't crash when encountering this kind of document structure.
> chore: update rich-text packages

- cypress/integration/rich-text/RichTextEditor.spec.ts
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/Table/index.tsx
This solves an issue in which deleting via the backspace or delete keys within or before a table would delete the current or forthcoming table cell.
> fix: no cell deletion via keyboard

- cypress/integration/rich-text/RichTextEditor.spec.ts
- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/plugins/DragAndDrop/index.tsx
- packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx
- packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx
Any HTML element become interactive  when adding `draggable="true"`. I found that by adding this attribute the whole block becomes draggable and Slate kind of take care of the rest.
I can drag:
- Embedded blocks
- Embedded inlines
Where:
- After, before and in the middle of paragraphs
- After and before other embedded blocks
- Inside blockquote elements
- Inside tables (only embedded inline elements)
> feat: make embedded blocks draggable []

- packages/rich-text/src/helpers/environment.ts
- packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx
- packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx
It seems Slate has compatibility issues with some browsers. Specially the ones that don't support the `beforeInput` event and this seems to affect the `contentEditable` attribute.
Their codebase has a lot of calls to browser detection, they even have a file with some [browser detection helpers](https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/utils/environment.ts).
I copied some from there and I tested on the following browsers on Mac OS:
- Latest Chrome
- Latest Opera
- Latest Safari
- Latest Edge
- Latest Firefox
They all worked fine as expected, even the command to cut & copy.
> fix: internal copy and paste for firefox, chromium and safari []

- packages/list/src/ListEditor.spec.tsx
- packages/list/src/ListEditor.tsx
The list field stopped accepting typed commas, that happened after the Forma36 update to version 4, where `TextInput` lost its internal state. When converting from array of values and back to the string, we lose the trailing commas.
This PR adds the `ListEditorInternal` component which implements the internal state allowing us to preserve the trailing commas.
> fix: fix list field preventing commas after forma36 v4

- apps/entry-app-collapsible/package.json
- apps/rich-text-app/package.json
- packages/default-field-editors/package.json
- packages/rich-text/package.json
Highlights of `2.0.0-next.1`:
- Internal drag & drop of embedded blocks and embedded inlines
- Internal copy & paste of embedded blocks and embedded inlines
> chore: bump next version to 2.0.0-next.1 []

- cypress/.eslintrc.js
- cypress/integration/LocationEditor.spec.ts
- cypress/integration/rich-text/RichTextEditor.spec.ts
- package.json
- yarn.lock
With the main motivation to fail linting when committing spec files with accidental `.only` or `.skip` test definitions.
https://github.com/contentful/field-editors/pull/940 does the same for `master`.
> chore: use cypress & mocha linting rules on next branch

- cypress/integration/rich-text/RichTextEditor.spec.ts
It seems to unfocus block elements we can use a simple `editor.click('bottom')` again instead of using right arrow key to move focus away.
Also note that changes in 1b52fe1, using `.type()` instead of triggering a `keydown` event didn't work locally but only on CI.
> test: use click again to unfocus block embeds

- cypress/.eslintrc.js
- cypress/integration/LocationEditor.spec.ts
- cypress/integration/RichTextEditor.spec.ts
- package.json
- yarn.lock
With the main motivation to fail linting when commiting spec files with accidental `.only` or `.skip` tests definitoins.
> chore: use cypress & mocha linting rules

- packages/rich-text/src/helpers/editor.spec.ts
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/Text/index.ts
We don't need to pass the node or a list of nodes as intended previously if we use the helpers provided by Slate/Plate. We only need the editor + path, in this case, I'm receiving the entry (node + path) but I'm not using the `node` at all. 
Question:
- For the developer experience, should we pass only `editor + entry` or `editor + path` as parameters to the helper?
That's how it's supposed to be used:
```ts
function CustomPlugin(): PlatePlugin {
return {
withOverrides: (editor) => {
const { normalizeNode } = editor;
editor.normalizeNode = (entry) => {
const [node, path] = entry; // we use only path from entry
if (isInvalidCase()) {
const paragraphs = slateNodeEntryToText(editor, path);
Transforms.insertNodes(editor, paragraphs);
}
normalizeNode(entry);
};
return editor;
},
};
}
```
> feat: create helper to filter out text as paragraphs from slate entries

- cypress/integration/MarkdownEditorInsertAssets.spec.ts
- packages/markdown/package.json
- packages/markdown/src/MarkdownEditor.mdx
- packages/markdown/src/utils/insertAssetLinks.ts
- packages/reference/src/__fixtures__/new_asset.json
- yarn.lock
We want to guarantee that new asset uploads will use `ctfassets.net` as a domain instead of `contentful.com`
> fix: markdown upload asset domain url to ctfassets.net []

- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
Use the optimized loader function in rich-text entry card that is also used in standard entry card
> fix: infinite asset loading in new rte

- packages/rich-text/src/plugins/Hyperlink/useRequestStatus.js
Hyperlink plugin in the Rich Text Editor requests a content type for each instance of a linked entity. This results in hundreds of requests when loading an editor with many links. We can make it better by at least caching the returned content types and getting them from cache.
> fix: cache content types for Hyperlink

- cypress/integration/rich-text/RichTextEditor.spec.ts
- packages/rich-text/src/plugins/List/createListPlugin.ts
- packages/rich-text/src/plugins/List/withList.ts
- packages/rich-text/src/plugins/Quote/utils.ts
A regression caused by the Plate upgrade. We were incorrectly passing the `validLiChildrenTypes` option which caused Plate's list plugin to remove valid items e.g. blockquotes.
> fix: allow LIST_ITEM_BLOCKS inside list items

- packages/rich-text/src/plugins/Hyperlink/index.js
Ensure any hyperlink like
```
{
"nodeType": "hyperlink",
"data": {
"uri": "https://foo.bar"
},
"content": [
{
"nodeType": "text",
"value": "",
"marks": [],
"data": {}
}
]
}
```
gets deleted during document normalization.
> fix: remove empty text hyperlinks

- cypress/integration/rich-text/RichTextEditor.spec.ts
- cypress/integration/rich-text/__snapshots__/RichTextEditor.spec.ts.snap
- packages/rich-text/src/RichTextEditor.styles.ts
- packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx
- packages/rich-text/src/plugins/Voids/createVoidsPlugin.ts
This fixes the behavior of RTE when a user has an entity block selected within a list. Before the block was removed and the cursor moved out of the list.
Instead we want to add a new paragraph to the same list item the block is in
> fix: enter new line in list item after entity block

- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/helpers/environment.ts
- packages/rich-text/src/plugins/EmbeddedEntityBlock/Util.ts
- packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx
- packages/rich-text/src/plugins/Heading/components/ToolbarHeadingButton.tsx
- packages/rich-text/src/plugins/Hr/index.tsx
- packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx
- packages/rich-text/src/plugins/List/components/ToolbarListButton.tsx
- packages/rich-text/src/plugins/Marks/Bold.tsx
- packages/rich-text/src/plugins/Marks/Code.tsx
- packages/rich-text/src/plugins/Marks/Italic.tsx
- packages/rich-text/src/plugins/Marks/Underline.tsx
- packages/rich-text/src/plugins/Quote/components/ToolbarQuoteButton.tsx
- packages/rich-text/src/plugins/Table/components/TableActions.tsx
- packages/rich-text/src/plugins/Table/components/ToolbarButton.tsx
The commit 07b10359007aebce4758c8875b773ae50506d00e tries to fix the issue by restoring it to original position, it's an attempt I think of on how to improve the UX for the user and fix the issue at the same time.
If it turns out not to be a good solution coding-wise and also in a perspective of a product own, we can drop only this commit.
Thoughts? @DanweDE @z0al @djagya @Cyberxon
> fix: scroll focus issue on safari

- packages/rich-text/src/plugins/List/__tests__/createListPlugin.test.tsx
- packages/rich-text/src/plugins/List/createListPlugin.ts
- packages/rich-text/src/plugins/List/utils.ts
Pressing backspace on a list with multiple items was causing the deleting to not work properly.
Example: 
How it is now:
---
> fix(rte-list): backspace with multiple list items []

- cypress/fixtures/map-search-address-reply.json
- cypress/integration/LocationEditor.spec.ts
- cypress/integration/rich-text/RichTextEditor.Pasting.spec.ts
- cypress/integration/rich-text/__snapshots__/RichTextEditor.Pasting.spec.ts.snap
- cypress/support/commands.js
- cypress/support/index.d.ts
- packages/rich-text/src/plugins/Hyperlink/index.tsx
Recognizes entity hyperlinks copied from safari, which don't have an `href` attribute
> fix: links within safari

- cypress/integration/LocationEditor.spec.ts
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/Quote/toggleQuote.ts
Any idea on how to test that on Cypress? I've tried something like:
```js
richText.editor.type('heading 1');
richText.toolbar.toggleHeading(BLOCKS.HEADING_1);
richText.editor.type('{enter}');
richText.editor.type('heading 2');
richText.toolbar.toggleHeading(BLOCKS.HEADING_2);
richText.editor.type('{uparrow}');
richText.editor.get('[data-slate-editor] h1').click().click().click();
```
But it does not work. Any ideas?
> fix(rte): triple selection selecting the next element instead

- packages/rich-text/src/helpers/editor.ts
`isLinkActive` throws an error in some cases as it seems the `editor` can be undefined on first render
> fix(rich-text): editor can be undefined on first render

- packages/rich-text/src/ContentfulEditorProvider.ts
- packages/rich-text/src/RichTextEditor.tsx
`ConnectedRichTextEditor` can be used directly, this PR ensures that by inlining the SDK provider.
> fix(rich-text): use sdk provider in ConnectedRichTextEditor

- packages/rich-text/src/ContentfulEditorProvider.ts
- packages/rich-text/src/RichTextEditor.tsx
This allows the editor to correctly update once a new version of the entry is given, as the old plate state does not interfere with the new one
> fix: clear rte state on unmount

- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Add `onClick` support to `WrappedEntryCard` component instead of always invoking the `onEdit`
> feat: support onClick on WrappedEntryCard component

- packages/rich-text/src/useNormalizedSlateValue.ts
Avoid failures when inserting nodes for first value normalization in rich text editor
> fix: initial normalization failing

- cypress/integration/rich-text/RichTextEditor.Pasting.spec.ts
This is a workaround that waits a bit for the selection to be registered by slate. The throttle time is currently 100ms so doubling that time should be enough.
> test: fix flaky test

- packages/rich-text/src/plugins/EmbeddedEntityBlock/LinkedEntityBlock.tsx
> fix(rich-text): fix entity cards alignment in <li>

- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx
- packages/rich-text/src/plugins/Hyperlink/components/EntityHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/UrlHyperlink.tsx
Sometimes, more frequently in safari, the hyperlink modal fetches the editor selection before it's changed when clicking on an hyperlink, keeping it for example at the beginning of the editor.
This causes the hyperlink modal to not grab the correct link data and so to display empty or wrong inputs.
The pr ensures the clicked node isn't determined by the editor selection but by the clicked point in the editor.
> fix: link data in safari

- packages/rich-text/src/plugins/List/utils.ts
Fixes two cases where the toolbar doesn't show an active state even though the selection range is a list
> fix: list toolbar state when selection is a range

- packages/reference/src/common/useEditorPermissions.ts
Always show the option to link existing assets on a reference field. This prevents, in case of an `allow` permission based on tags, the impossibility to see assets the users have access to.
It is meant as a quick, yet effective, workaround in the wait for a refined permission evaluation
> fix: allow linking assets on permission rule with tags

- cypress/integration/rich-text/RichTextEditor.spec.ts
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/Table/components/Table.tsx
- packages/rich-text/src/plugins/Table/createTablePlugin.ts
This errors happens when putting the text cursor before a table, it doesn't block anything for the user but it's annoying, it also doesn't allow me to write Cypress tests for this feature.
Cypress will complain saying the editor thrown an error.
The error is also triggered for any key I press while the cursor is before table.
---
I needed to use `window.getSelection` in this case because Slate's `path` is the same when the cursor is one the first cell or before table, so I couldn't differentiate their positions based on what Slate offers.
The solution was to create a wrapper for the table, so I can identify if the selection is between the container and the table.
> fix(rte): pressing enter before a table

- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
Instead of passing the fetched entry's `sys.id` to `onAction` callbacks, simply pass the already known entry ID prop. We know the ID as it's part of the actual link.
This has a big advantage that even when the entry can't be loaded, or if an `onAction` is called before it loaded, we can still send teh entry ID.
> fix: pass already known entry link id to onAction

- cypress/integration/rich-text/RichTextEditor.spec.ts
- packages/rich-text/src/helpers/editor.ts
- packages/rich-text/src/plugins/Table/createTablePlugin.ts
We no longer need to disable backspace and delete keydown event inside tables after implementing this: https://github.com/contentful/field-editors/pull/1087/files#diff-f91f4d3d54e0f418e12d1ba9ba63a4b90594f3bb7a8a11a4c2137027165287c5R70
This solves a bunch of issues we are currently having with deleting things inside and around tables.
> fix(rte): delete event handler for tables after implementing plates methods

- packages/reference/src/common/useEditorPermissions.spec.ts
- packages/reference/src/common/useEditorPermissions.ts
One of our customers has defined their permissions as follows:
* User can read entries belonging to one of four content types (a,b,c,d)
* User can read entries that have a specific tag assigned to them
The bug is that they have a reference field editor which is restricted to content types other than a,b,c,d. So these content types shouldn't be linkable but there still might be entries with the tag
> fix: always show link existing button to account for tag based permissions [ZEND-1864]

- packages/number/src/NumberEditor.spec.tsx
- packages/number/src/NumberEditor.tsx
it changes the input type to `number` and it is still calling the onChange event, check:
> fix: change input type to number

- packages/rich-text/src/Toolbar/components/EmbedEntityWidget.tsx
Same issue as [here](https://github.com/contentful/field-editors/blob/master/packages/reference/src/common/useEditorPermissions.ts#L49-L62): Tag-based permissions break the access evaluation. We assume that one can always link assets as fallback solution.
> fix(EmbedAsset): always assume that assets are available for linking [HOMER-829]

- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/SingleReferenceEditor.tsx
- packages/reference/src/entries/SingleEntryReferenceEditor.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Expose two props `hasRemoveActions` and `hasMoveActions ` in `MultipleEntryReferenceEditor` and one prop `hasRemoveActions` in `SingleEntryReferenceEditor` to be able to hide the actions menu completely.
This is to fix a bug when a user without editing permissions could still open the actions menu in the web app.
> feat: reference hide actions prop [DANTE-488]

- packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx
- packages/rich-text/src/plugins/Hyperlink/components/EntityHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/UrlHyperlink.tsx
Instead of completely disabling hyperlinks in the read-only mode allow users to open the modal in a non-editable state instead.
> fix(rich-text): allow hyperlink viewing in readonly mode

- packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
- packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedAssetCard.test.tsx
- packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedEntryCard.test.tsx
Users should still be able to edit (or view) embedded entities when the RT editor is disabled.
> fix(rich-text): don't disable "Edit" actions on embeds

- packages/rich-text/src/RichTextEditor.styles.ts
Adding `not-allowed` cursor to the disabled rich text editor
https://github.com/contentful/field-editors/pull/1125
> fix: add not allowed cursor to the disabled rich text editor

- packages/reference/src/components/CreateEntryLinkButton/CreateEntryLinkButton.tsx
The add content button is disable if it receives no creatable content types, but there might still be readable one for the "link existing" option
> fix: avoid disabling button if no creatable content type []

- packages/json/src/JsonEditoField.tsx
- packages/location/src/GoogleMapView.tsx
- packages/markdown/src/components/MarkdownTextarea/MarkdownTextarea.tsx
- packages/radio/src/RadioEditor.tsx
- packages/rich-text/src/RichTextEditor.jsx
- packages/tags/src/TagsEditor.tsx
Some field editors do not look disabled when you disable them (by setting `isInitiallyDisabled` to true)
- JSON ( looks the same but you can’t edit )
- Rich text ( the courser is not `not-allowed` )
- Mark down ( the courser is not `not-allowed` )
Even after passing `isInitiallyDisabled` as `true`  you can still edit/delete or add values to these fields 
- Map editor (you can still change the marker location (edit))
- Radio (you can click the clear button )
- Tags (you can still delete tags and the courser is not `not-allowed` )
https://github.com/contentful/field-editors/pull/1128
> fix: reflect disabled state on fields

- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
The `useCallback` prevented updating the creatable / readable CTs since we resolve them asynchronously. Actual readable / creatable CTs were never propagated to the UI.
> fix: only show readable / creatable CTs in reference field editor [ZEND-2154]

- cypress/integration/rich-text/RichTextEditor.spec.ts
- packages/rich-text/src/helpers/sanitizeIncomingSlateDoc.ts
- packages/rich-text/src/prepareDocument.ts
We rely on initial normalization to prevent crashes when we find e.g. hyperlink without children, however, Slate still crashes in some cases (when attempting to do the normalization) and complains about empty nodes (nodes without text).
In this particular case, having an empty hyperlink is fine (i.e. handled by the normalization) but the editor crashes as soon as that link is followed by a list with exactly two text nodes 🤷🏻‍♂️ 
This PR brings back the old `santizeIncomingSlateDoc` helper 😞 as it seems the most reliable way we got to prevent such errors.
> fix(rich-text): sanitize slate content

- packages/date/src/TimepickerInput.tsx
> fix: increased time input width in date picker to fix visual bug [TOL-122]

- packages/reference/src/components/ScheduledIconWithTooltip/ScheduledIconWithTooltip.tsx
Reverting some changes introduced in #1137
> fix(reference): avoid infinite getEntityScheduledActions calls

- packages/rich-text/src/Toolbar/components/EmbedEntityWidget.tsx
Hiding the `+Embed` dropdown button when there are no actions under it,
> This is already implemented on the master branch  
https://github.com/contentful/field-editors/blob/58dedc65a2de20973775b48cbb95b54d81894d0a/packages/rich-text/src/Toolbar/index.js#L130-L158
> fix: hide embed button when all actions are disabled

- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
This fixes a small design issue with the content type search in the create entry button component.
Before:
After:
> fix: search input styles [HOMER-1048]

- packages/reference/src/components/SpaceName/SpaceName.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Add an optional space name with icon to the wrapped entry card.
> feat: add optional space name to entry card

- packages/reference/src/common/SortableLinkList.tsx
Click events are not firing properly on children with default value for `distance` property.
> fix: click handler on children of sortable list

- packages/rich-text/src/plugins/CommandPalette/hooks/useCommandList.tsx
Rich Text Editor crashes anytime a customer types "/", when the rich text field does not allow embedded entries in validation
> fix: no embedded entries check rich text commands [TOL-273]

- packages/reference/src/components/SpaceName/SpaceName.tsx
Truncate long space names on entry card and reveal the name on the tooltip.
Ticket: https://contentful.atlassian.net/browse/DANTE-634
> fix: truncate long space names on entry card [DANTE-634]

- packages/_test/package.json
- packages/default-field-editors/package.json
- packages/dropdown/package.json
- packages/radio/package.json
- packages/reference/package.json
- yarn.lock
Version is set to `^10.0.0` instead of a later one to provide maximum compatibility when `field-editors` is used with other libraries using `contentful-management`.
> chore: update `contentful-management` to the latest version

- packages/rich-text/src/plugins/shared/useFetchedEntity.ts
Rollback change of deps in useFetchedEntity since it was not necessary to fix the bug of the version compare in the web app
> fix: rollback change of deps in useFetchedEntity

- packages/reference/package.json
We are using `p-queue` in `@contentful/field-editor-reference`, but it is currently not a dependency. Users, therefore, receive an error when using the package.
https://github.com/contentful/field-editors/blob/8567b37782848c996509a04e3a7e01a02be839f7/packages/reference/src/common/EntityStore.tsx#L16
The issue was probably introduced in https://github.com/contentful/field-editors/pull/1214
> fix: add p-queue as dependency

- packages/json/src/JsonEditorField.tsx
Return the line wrapping to the JSON editor.
> feat: add line wrapping to the JSON editor

- packages/reference/src/common/EntityStore.tsx
When passing down the `currentEnvironmentId` we always need to check if there is an environment alias set.
> fix(EntityStore): respect environment alias

- packages/reference/src/common/EntityStore.tsx
- packages/reference/src/components/ScheduledIconWithTooltip/ScheduleTooltip.tsx
- When using `app.contentful.com` you might notice that we will call `GET /scheduled_actions` 1 time per references when opening an entry. This might result in 429s for entries that have multiple references (e.g. 500).
- With this change, we fetch all scheduled actions at first since the max limit is 500 per space&environment and then return after the fetching (using the cache key) only the ones that match the current entity ID that is passed to the function. That way we reuse the request call, and only filter the data afterwards.
This PR also fixes the `false` that is being displayed in the scheduled action tooltip
> fix(EntityStore): use fixed cache key for scheduled actions [SPA-871]

- packages/reference/src/common/EntityStore.tsx
The current default concurrency limit is too low, causing increases in field editor loading times with large numbers of references.
> fix: increase pqueue concurrency in entitystore

- packages/reference/package.json
- packages/reference/src/resources/useResourceLinkActions.ts
- yarn.lock
Use urn from entries that are fetched from the api. EntityMetaSysProps type in [contentful-management.js](https://github.com/contentful/contentful-management.js) repository is missing urn. It's added in this [PR](https://github.com/contentful/contentful-management.js/pull/1479)
> feat: use urn from entries that are fetched from api

- packages/date/src/DatepickerInput.tsx
The DatepickerInput should be time and timezone agnostic, thats why we use `moment().format()` instead of `moment().toDate()`. `moment().toDate()` takes into account time and timezone and converts it based on your system timezone which can result in the date change. e.g. for user who has a timezone +02:00, `moment('2022-09-16T00:00+4:00').toDate()` will return `2022-09-15`
> fix: fix the way date is parsed in the DateEditor [BAU-943]

- packages/date/src/DatepickerInput.tsx
When we pass the date-only strings 'YYYY-MM-DD' to the `new Date()` it is treated as UTC, but we need it to be treated with the system's local timezone.
So for example, if you have UTC offset `-0700`  and do `new Date('1970-01-01')` it will return `Wed Dec 31 1969 17:00:00 GMT-0700`. 
But if you do `new Date(1970, 0, 1)` it will return `Thu Jan 01 1970 00:00:00 GMT-0700`.
❗️ I will add test coverage in the separate PR, so we can merge this PR asap and fix the latest `field-editor-date` pkg.
> fix(field-editor-date): fix date formatting []

- packages/reference/src/resources/testHelpers/resourceEditorHelpers.ts
- yarn.lock
I think #1256 introduced a duplicate version of the Forma 36 components, which could be the explanation for the drastic increase in web app bundle size. I'll see if this brings it back down.
> fix(deps): deduplicate dependencies

- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
Removing the grayed out background because it makes the field look disabled in Compose
> fix: remove background override from xspace refs

- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/common/customCardTypes.ts
- packages/reference/src/entries/MultipleEntryReferenceEditor.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- We want to know which field is currently being dragged in a multiple reference field.
Unfortunately, `react-sortable-hoc` does not offer that out of the box.
This PR calculates and exposes this behaviour with the `isBeingDragged` boolean
- It also adds a class to the body when dragging is active, to have a drag cursor style (solution from https://github.com/clauderic/react-sortable-hoc/issues/328)
> feat: isBeingDragged multiple reference field [TOL-361]

- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/common/ReferenceEditor.tsx
- packages/reference/src/entries/MultipleEntryReferenceEditor.tsx
Last PR (https://github.com/contentful/field-editors/pull/1272) was overriding the default sort end behaviour, which broke the drag and drop.
This fixes the issue
> fix: on sort end multiple reference field

- packages/json/src/JsonEditorField.tsx
When the json field editor is focused today the user tries to do a browser search (CMD + F) the component breaks because we haven't configured codemirror's search module. 
Disable codemirror's search, so that the key binding falls back to the native browser search.
> fix: disable search keymap option to prevent breaking on search [ZEND-2879]

- .github/CODEOWNERS
I think the `*` syntax is taking over `dependabot.reviewers` config. This works because dependabot PRs typically modify only `package{-lock}.json` and/or `yarn.lock` files
> chore(deps): fix codeowners shadowing dependabot config

- cypress/integration/rich-text/RichTextEditor.Tracking.spec.ts
- cypress/integration/rich-text/RichTextEditor.spec.ts
- packages/rich-text/src/Toolbar/_tests_/toolbar.test.tsx
- packages/rich-text/src/Toolbar/index.tsx
- packages/rich-text/src/plugins/Marks/Code.tsx
- packages/rich-text/src/plugins/Marks/Subscript.tsx
- packages/rich-text/src/plugins/Marks/Superscript.tsx
- packages/rich-text/src/plugins/Marks/components/MarkToolbarButton.tsx
> feat: dropdown toolbar rich text [TOL-764]

- packages/rich-text/src/plugins/Table/onKeyDownTable.ts
Fixes some A11Y issues with tabbing in rich text.
Rich Text Tables plugin introduced a bug where you could not tab _out_ of the rich text field anymore. This PR should fix that.
Also when you are in a table and you want to exit the rich text editor with a keyboard, you can now use the ESC key. Previously this was impossible with a keyboard.
> fix: a11y issues focus rich text

- packages/reference/src/common/SortableLinkList.tsx
This fixes the issue with https://contentful.atlassian.net/browse/TOL-823. When reordering multi referenced items the item being dragged would disappear. Giving it a higher zIndex fixes the issue. I chose one of the constants from the f36-tokens package
> fix: solve multi ref drag issue [TOL-823]

- .contentful/vault-secrets.yaml
- Enables the repo to use secrets from vault instead of environment variables in CI.
> ci: add vault configuration []

- packages/reference/src/components/LinkActions/LinkEntityActions.tsx
- packages/reference/src/resources/MultipleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/MultipleResourceReferenceEditor.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.tsx
Allow custom actions to be passed to resource reference editors via the existing `renderCustomActions` parameter.
> feat: custom actions in resource reference editors [DANTE-793]

- cypress/component/reference/WrappedAssetCard.spec.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
Pressing enter key should fire the onEdit event for asset field
> fix: enter key open asset modal [TOL-889]

- packages/rich-text/src/plugins/CommandPalette/components/CommandList.styles.ts
- packages/rich-text/src/plugins/CommandPalette/components/CommandList.tsx
- packages/rich-text/src/plugins/CommandPalette/onKeyDown.spec.ts
- packages/rich-text/src/plugins/CommandPalette/onKeyDown.ts
- packages/rich-text/src/plugins/Marks/Code.tsx
- missing z-index on the poper (not visible in the web app and also some visual issues in compose)
- added support for command prompt in other keyboards (QWERTZ, ...)
> fix(rte): [TOL-989] command prompt not always visible and working

- packages/reference/src/common/SortableLinkList.tsx
There's an image overlay happening in Compose when user is trying to add existing media to a field with multiple images setting.
> fix: images overlay modal in compose [TOL-921]

- packages/markdown/src/components/MarkdownPreview.tsx
- packages/markdown/src/utils/replaceMailtoAmp.spec.ts
- packages/markdown/src/utils/replaceMailtoAmp.ts
We use `dompurify` to sanitize the markdown preview output. Dompurify uses innerHTML at some point, which transforms `&` to`&amp` inside of href links. This causes an issue with mailto links not working as expected. Everything after `&amp` gets ignored.
For example: `<a href="mailto:test@test.com?subject=test&body=test">Test</a>`
turns into:
`<a href="mailto:test@test.com?subject=test&amp;body=test">Test</a>`, which makes the `mailto` link ignore the body parameter.
I added a regex that transforms the `&amp` to `&` again inside mail to links. Unfortunately I was not able to add any exclusion inside the dompurify package (see this issue in the package: https://github.com/cure53/DOMPurify/issues/379#issuecomment-571997013)
> fix: mail to links replace ampersand [TOL-923]

- packages/rich-text/src/plugins/CommandPalette/onKeyDown.ts
A customer reached out that they are having troubles with the rich text commands plugin.
They have content that contains a slash /. Entering the slash forces the RTE to start a new span (because of the rich text commands plugin) and the slash is not connected to previous content anymore.
They have a workaround for this, to press ESC; But this also blurs the editor and they have to click on the RTE again.
This PR removes the span (rich text commands mark) when the user types a space after typing a slash /.
The only downside to this approach is that the search functionality will not work anymore when you type a space (since the rich text command gets removed).
> fix: remove command mark after space [TOL-945]

- packages/_shared/src/utils/entityHelpers.ts
- packages/rich-text/src/plugins/Hyperlink/useEntityInfo.ts
`getAssetTitle` incorrectly used type Entry as a type. Asset is not compatible with the function signature of `getFieldValue` because of the special type signature of Assets.fields.file => to fix this we now pass the title field only to `getFieldValue`. 
`useEntityInfo` now requires the target to be a `Link<ContentEntityType>` instead of a generic string.
> fix: improve types

- packages/markdown/src/components/MarkdownBottomBar.tsx
Fixes the issue that the TextLink inside the help text is not always centered.
Using flex would need more adjustments as it also affects the whitespaces.
> fix(markdown-editor): textlink sometimes not centered in help text []

- .contentful/vault-secrets.yaml
this is required before we migrate to use the token from the vault
> chore: update circle ci permissions [TOL-938]

- packages/rich-text/src/helpers/sdkNavigatorSlideIn.spec.ts
- packages/rich-text/src/helpers/sdkNavigatorSlideIn.ts
- packages/rich-text/src/plugins/EmbeddedEntityBlock/Util.ts
In the rich text editor, when embedding an entry or asset block, ensure that we take into account the entity selector option of `withCreate: true` which can cause the slide-in editor to open (web app).
When the slide-in editor opens, then we only want to re-focus the rich text editor after the slide-in editor (and any other slides opened on top of that) closes.
> fix: do not focus RTE when another slide is open [TOL-989]

- packages/rich-text/src/helpers/sdkNavigatorSlideIn.spec.ts
- packages/rich-text/src/helpers/sdkNavigatorSlideIn.ts
- packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx
Same as #1353 but for inline embeds. When we create a new entry for an inline embed in the web app, the slide-in editor opens. In this case we  want to focus the slided in entry editor's first field, not the rich text editor in the background tab. Only after the slide closes again, we will focus the rich text editor again.
> fix: 🐛 do not focus RTE on inline embed + create entry

- .circleci/config.yml
- with_npm_token has only a read-only token, which currently overrides the one with write access
- also move the write token to release step only
> chore(release): use the correct secret for publish the npm release []

- cypress/integration/rich-text/RichTextEditor.Pasting.spec.ts
- cypress/integration/rich-text/__snapshots__/RichTextEditor.Pasting.spec.ts.snap
- packages/rich-text/src/plugins/PasteHTML/utils/sanitizeHTML.ts
The previously introduced regex for cleaning up unwanted linebreaks and whitespaces had an issue with some inline tags and produced therefore invalid markup.
We now split up the regex into two replacements, this will fix the behaviour and the RTE no longer crashes the page.
> fix(RTE): split up sanitize regex to prevent invalid markup

- cypress/integration/rich-text/RichTextEditor.Tracking.spec.ts
- packages/rich-text/src/plugins/Tracking/createTrackingPlugin.ts
Since we can't (without a major reworking) differentiate between shortcut and viewport action origins in this case, this adds a basically "could be either" origin. Even though it doesn't add any information atm, it does clear things up on the tracking side, and if we ever for some reason add pasting to the toolbar, it will be differentiated from there.
> fix: correct misleading action origin on paste event - rich text

- packages/rich-text/src/plugins/EmbeddedEntityBlock/Util.ts
- packages/rich-text/src/plugins/EmbeddedEntityInline/index.tsx
Removing selection in https://github.com/contentful/field-editors/pull/1354 and https://github.com/contentful/field-editors/pull/1353 introduced a regression specifically for users of hotkey insertion. Focusing improvements in those PRs are retained.
> fix: [RTE] embed entries in correct place when using hotkeys

- packages/reference/src/components/MissingEntityCard/MissingEntityCard.tsx
- packages/reference/src/components/ResourceEntityErrorCard/ResourceEntityErrorCard.tsx
- packages/reference/src/components/ResourceEntityErrorCard/UnsupportedEntityCard.tsx
- packages/reference/src/components/index.ts
- packages/reference/src/index.tsx
- packages/reference/src/resources/Cards/ResourceCard.spec.tsx
- packages/reference/src/resources/Cards/ResourceCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedResourceCard.tsx
- packages/rich-text/src/plugins/shared/__fixtures__/space.json
- packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedResourceCard.test.tsx
Follow-up for https://github.com/contentful/field-editors/pull/1422.
* Pass _selected_ state to _missing entity_ card.
* Render the _unsupported entity_ card for unknown resource types.
* Create reusable _ResourceEntityErrorCard_ to reduce code duplication.
* Add more tests.
> feat: add more embedded resource block states

- cypress/e2e/rich-text/RichTextEditor.spec.ts
- cypress/e2e/rich-text/document-mocks/validDocumentThatRequiresNormalization.js
- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/internal/misc.ts
- packages/rich-text/src/test-utils/createEditor.ts
In some instances, the `onChange` callback for RT does not get triggered. One of which is updating the URL value of a hyperlink after a fresh load of a page (i.e., initial render).
There is one test I skipped that I will fix in a follow-up PR
> fix(rich-text): onChange callback is not triggered [TOL-1284]

- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
In our use case, we need to pass props to the menu like `usePortal={false}`.
> feat: allow passing menuProps to the entry creation trigger [SPA-1278]

- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
Currently, the `menuProps` enforce you pass `children` even though it has no effect.
Fix from https://github.com/contentful/field-editors/pull/1441
> fix: type doesn't enforce children prop [SPA-1278]

- .eslintrc.js
- baseJestConfig.js
- cypress/component/reference/MultipleEntryReferenceEditor.spec.tsx
- cypress/fixtures/store.ts
- package.json
- packages/_shared/package.json
- packages/_shared/src/FieldConnector.ts
- packages/_test/package.json
- packages/boolean/package.json
- packages/checkbox/package.json
- packages/default-field-editors/jest.config.js
- packages/dropdown/package.json
- packages/json/package.json
- packages/list/package.json
- packages/location/package.json
- packages/markdown/package.json
- packages/multiple-line/package.json
- packages/multiple-line/src/MultipleLineEditor.test.tsx
- packages/radio/package.json
- packages/rating/package.json
- packages/reference/package.json
- packages/single-line/package.json
- packages/single-line/src/SingleLineEditor.test.tsx
- packages/slug/package.json
- packages/slug/src/SlugEditor.test.tsx
- packages/tags/package.json
- packages/url/package.json
- packages/url/src/UrlEditor.test.tsx
- yarn.lock
@contentful/field-editor-shared is importing lodash-es which seems to cause some issues: https://discord.com/channels/1030176999471321129/1111350294434025613/1132070425254445186
In General:
ESM can import CJS
CJS can't import ESM
@contentful/field-editor-shared is published as CJS and "ESM". Therefore it should only import CJS dependencies. FieldConnector.ts is importing from lodash-es. Also, the package depends on lodash-es. Removing the dependency and avoid importing from lodash-es to have a proper CJS package
> fix: remove lodash-es to fix cjs issues [TOL-1346]

- packages/reference/src/__fixtures__/entry/published_entry_non_master.json
- packages/reference/src/common/EntityStore.tsx
- packages/reference/src/components/SpaceName/SpaceName.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/reference/src/resources/Cards/ResourceCard.spec.tsx
in this PR we want to be able to correctly fetch an entry from a crn that contains environment information whether it is an implicit master (crn contains`/environments/master`) or any other non master environment (crn contains `/environments/staging` for example). We also would. like to show the environment information in the tooltip of the wrapped entry card as shown in the screenshot below:
> feat: adding environment support in the WrappedEntryCard

- packages/reference/src/common/EntityStore.tsx
- packages/reference/src/common/queryClient.tsx
- packages/reference/src/index.tsx
exports `EntityCacheProvider` (for the lack of a better name) that can used in a host application to wrap multiple reference editors resulting query client/cache sharing.
> feat(reference): enable sharing query cache between editors

- packages/rich-text/src/Toolbar/components/EmbedEntityWidget.tsx
Show _embed_ button in Rich Text toolbar when resource block is the only enabled node.
> fix: show RT embed button also for resource only

- packages/json/src/JsonEditor.tsx
- packages/json/src/JsonEditorField.tsx
- packages/json/src/utils.ts
The JSON editor used a different tab width for indentation:
- value was parsed with 4 spaces
- codemirror used 2 spaces
This resulted always into different indentation on pressing enter
> fix(json-editor): consolidate tab width

- cypress/e2e/rich-text/RichTextEditor.Commands.spec.ts
- packages/rich-text/src/plugins/CommandPalette/components/CommandList.tsx
- packages/rich-text/src/plugins/CommandPalette/components/CommandPrompt.tsx
- packages/rich-text/src/plugins/CommandPalette/useCommands.ts
- Fixes: https://github.com/contentful/field-editors/issues/1346
- Inline embedded entries are working again with rich text commands
- Add missing key props to ignore warnings
- Set colour when rich text command is active
- Add asset icon when no thumbnail available for assets
Todo
> fix: rich text commands listens to validations [TOL-1473]

- packages/rich-text/src/plugins/CommandPalette/components/CommandList.tsx
- packages/rich-text/src/plugins/CommandPalette/useCommands.ts
After my last PR, in some edge cases, typing slash to activate the rich text commands, would break the rich text editor.
Fixes:
- ensure that commands only contains commands relevant to allowed content types
- for some reason, we always rendered the asset component for each command. Now we correctly render Asset for Assets and Item command for entries.
> fix: rich text commands issue []

- package.json
- packages/_test/src/createFakeFieldAPI.test.ts
- packages/_test/src/createFakeFieldAPI.ts
- packages/boolean/src/Boolean.spec.tsx
- packages/boolean/src/BooleanEditor.tsx
- packages/checkbox/src/CheckboxEditor.spec.tsx
- packages/date/src/DateEditor.tsx
- packages/date/stories/DateEditor.stories.tsx
- packages/location/src/LocationEditor.tsx
- packages/location/stories/LocationEditor.stories.tsx
- packages/number/src/NumberEditor.spec.tsx
- packages/number/src/parseNumber.spec.ts
- packages/rating/src/RatingEditor.spec.tsx
- packages/rating/src/RatingEditor.tsx
- packages/rating/stories/RatingEditor.stories.tsx
- packages/reference/src/utils/fromFieldValidations.ts
- packages/tags/package.json
- packages/tags/src/TagsEditor.tsx
- yarn.lock
Replacing `react-sortable-hoc` in favor of `dnd-kit` for better compatibility with React in TagEditor component.
> refactor: [] Replace `react-sortable-hoc` with `dnd-kit` (TagEditor)

- packages/reference/src/assets/WrappedAssetCard/AssetCardActions.tsx
Provide a new UI for the file information in the Asset menu. It follows a similar UI to the Cloudinary Contentful App (https://www.contentful.com/developers/changelog/#cloudinary-app-improvements-external-references-support-and-enhanced-user-experience).
File information properties are clickable but don't do anything. It does not make sense.
Render a description list element with the file information and disable it as a menu item.
> feat: file info new UI []

- packages/reference/src/components/SpaceName/SpaceName.tsx
Double the space for the space name in resource link cards.
Before
After
> feat: increase space for space name

- packages/rich-text/src/plugins/Hyperlink/components/UrlHyperlink.tsx
Fix issue with tooltips behaving weirdly in some cases for links in rich text
Before:
https://github.com/contentful/field-editors/assets/22968325/5e4d9625-88df-4b3b-8fdb-43d63c002aae
After:
https://github.com/contentful/field-editors/assets/22968325/87c885a9-a166-418f-b282-78603867be56
- use portal to display tooltip
- min-width instead of auto width (otherwise the width would stretch because of the portal positioning)
> fix: tooltip link placement richtext [ZEND-4296]

- packages/rich-text/src/plugins/EmbeddedResourceInline/FetchingWrappedResourceInlineCard.tsx
- packages/rich-text/src/plugins/Hyperlink/useResourceEntityInfo.ts
- packages/rich-text/src/plugins/Hyperlink/utils.ts
- packages/rich-text/src/plugins/shared/utils.ts
Add the environment ID to the embedded resource inline entry node’s tooltip and truncate the title in the tooltip to keep it short.
> feat: show environment in resource inline block

- .github/workflows/auto-merge.yml
Enables dependabot automerging for all patches and minor updates, except for plate and slate.
> chore: enable automerge for dependabot

- packages/location/src/LocationEditor.tsx
Before (when lat and lon are both null):
After (when lat and lon are both null):
- If either lat or lon is set but not the other than setting the other to 0
- If both lat or lon are not set then setting localValue to undefined to remove disabled state
- If both lat and lon are set then should show both
> fix: location null lat/lon issue []

- packages/rich-text/src/Toolbar/components/EmbedEntityWidget.tsx
Show embed button in Rich Text toolbar when inline resource is the only enabled node.
> fix: show RT embed button for only inline resource

- cypress/e2e/rich-text/RichTextEditor.Links.spec.ts
- cypress/e2e/rich-text/RichTextEditor.Tracking.spec.ts
- cypress/fixtures/utils.ts
- packages/rich-text/src/plugins/Hyperlink/components/EntityHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/LinkPopover.tsx
- packages/rich-text/src/plugins/Hyperlink/components/ResourceHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/UrlHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/linkHandlers.ts
- packages/rich-text/src/plugins/Hyperlink/components/styles.ts
It is currently not possible to edit the text after you added a hyperlink. You can however use the arrow keys on your keyboard to edit the link. This is causing some bad UX. This PR will improve that by introducing a link popover element.
A mouse click brings the caret to the right position so the user can change the link text, but it also opens the popup menu underneath. This popup menu has a button to remove the link, copy the link (when they are not entity links), open the link a new tab and a button to open the edit hyperlink modal. In this modal the user can edit the hyperlink href.
> feat: hyperlink edit popover modal

- cypress/fixtures/utils.ts
- packages/rich-text/src/internal/hooks.ts
- packages/rich-text/src/plugins/Hyperlink/components/LinkPopover.tsx
- packages/rich-text/src/plugins/Hyperlink/components/UrlHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/styles.ts
After merging https://github.com/contentful/field-editors/pull/1542 , copy pasting rich text content with links behaved differently. Before, a link would get copied over successfully. Afterwards, a link would not get copied anymore and it would include the link separately. This PR fixes that.
Ticket: https://contentful.atlassian.net/browse/TOL-1647
I render the edit link popover component with a portal. This introduces some issues with positioning. First of all, we have to now check when the popover component should be displayed. It will only display when the editor is focussed and the caret is inside a link OR when the mouse interacts with the popover.
I've also changed the Text to TextLink in the rich text editor, which will make sure that when an editor copies over the content, it will …
> fix: rich text link copy to google docs [TOL-1647]

- packages/rich-text/package.json
When using default-field-editors in an app, ConnectedRichTextField fails to render because it lacks the plate/common dependency. 
Some partner apps cannot install the correct plate version due to their environments not supporting that version.
> fix: add plate common dependency to rich-text

- packages/default-field-editors/package.json
- packages/reference/package.json
- yarn.lock
Increasing the CMA.js' version range to include v11. This allows better deduping in the consuming packages.
I didn't touch dev dependencies.
The failing component test is the same that's failing in `master` atm.
> feat: support CMA.js v11

- cypress/component/location/LocationEditor.spec.tsx
LocationEditor component tests [keep failing](https://app.circleci.com/pipelines/github/contentful/field-editors/6441/workflows/e47211c0-e270-498e-910e-d93fdc0305ec/jobs/23234) due to googleMapsKey not being set properly. These tests were recently migrated to component tests. Before they were ran on top of storybook stories which were passing the key [correctly](https://github.com/contentful/field-editors/blob/ce6b53a046d6e79718c8e196556563d81f44df84/packages/location/stories/LocationEditor.stories.tsx#L36). This migration is most likely related to these failures, but I am still not sure why they passed [here](https://github.com/contentful/field-editors/pull/1550)
> test: pass google maps key to LocationEditor component tests

- packages/reference/src/common/useContentTypePermissions.ts
- packages/reference/src/common/useEditorPermissions.spec.ts
- packages/reference/src/common/useEditorPermissions.ts
- packages/reference/src/components/LinkActions/helpers.ts
The way reference field works, it will take the available CTs for the field - via validations - filter out the ones that user has no permissions to read and pass the remaining list to the Entity Search modal. If an empty array of CTs is provided Entity Search will render all CTs of the environment.
When a user has partial access to content types e.g. via tags these content types will not appear in the list of readable CTs and will result in an empty array to be passed to Entity Search which will then result in all available CTs to be listed overriding the field validations.
If instead we pass the available CTs then Entity Search will still respect the validations and is smart enough to filter out individual entities the user might not have permissions to read.
See the following example:
* …
> fix: use available CTs instead of only readable

- cypress/e2e/rich-text/RichTextEditor.Headings.spec.ts
- packages/rich-text/src/plugins/Heading/components/ToolbarHeadingButton.tsx
We always picked the first item to check if it's a headline.
Inside lists it would be deeper nested so we need a further iteration.
> fix(rich-text): show the selected headline inside of lists

- .circleci/config.yml
Create a new patch once for all packages, as the publishing was broken and we have now missing package versions :/
Will be then reverted after the packages were released.
> chore(ci): publish a new patch for all packages

- .circleci/config.yml
Reverts contentful/field-editors#1585
Waiting for the package bump before merging it
> chore(ci): revert publishing to semantic one

- .github/dependabot.yml
Dependabot.yml had wrong indentation after GH migration which was breaking dependabot PRs
> chore: fix npm-github registry in dependabot.yml

- packages/rich-text/package.json
- packages/rich-text/src/plugins/DragAndDrop/index.tsx
- yarn.lock
Error being throw when dragging and dropping with custom rich text editor.
- Related to this history change & the new dndkit library
Todo
EDIT
Because we push a new undo as an empty array this condition doesn't short-circuit and the operations doesn't exist on the empty array. I'm not sure why this is only a problem for the App SDK and hasn't been happening the regular web app Rich Text 🤔
```
const lastOp =
lastBatch && lastBatch.operations[lastBatch.operations.length - 1]
```
https://github.com/ianstormtaylor/slate/blob/cd93871ae69721f7361e17e8b28feab004a9c855/packages/slate-history/src/with-history.ts#L72C5-L74C73
> fix: fixing custom app rich text dnd [TOL-1742]

- .circleci/config.yml
- .npmrc
- packages/reference/package.json
- packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx
- packages/reference/stories/ExternalReferenceCard.stories.tsx
- yarn.lock
As a follow up to this [PR](https://github.com/contentful/field-editors/pull/1602) and updating the Forma `EntryCard` component to accept a Badge option in this [PR](https://github.com/contentful/forma-36/pull/2671#issuecomment-1943372919), this PR bumps the versions of Forma packages in `field-editor-reference` and passes the custom badge to `EntryCard` using the `badge` option instead of the `icon` option.
> fix: use the new badge option on EntryCard for ExternalResourceCard [DANTE-1330]

- cypress/component/reference/MultipleResourceReferenceEditor.spec.tsx
- cypress/component/reference/SingleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/MultipleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/testHelpers/resourceEditorHelpers.ts
- packages/reference/src/resources/useResourceLinkActions.ts
- packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx
- packages/rich-text/src/plugins/shared/EmbeddedBlockUtil.ts
- packages/rich-text/src/plugins/shared/EmbeddedInlineUtil.ts
- packages/rich-text/stories/RichTextEditor.stories.tsx
Update _reference_ and _rich text_ field editors to use the new cross-space entity picker functions (`selectSingleResourceEntity` and `selectMultipleResourceEntities`). The new functions return resource links which means we no longer have to convert entries to links in the field editors and this PR is mostly clean up.
> chore: use new cross-space entity picker functions

- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
we had a bug where the status of a scheduled entry looked different in the reference editor compared to the list view
This is what it looked liked before the change
This is what it looks like now
> fix: update status badge for scheduled entry [TOL-1801]

- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
This reverts commit b15911a7e4882d4c6f9765a3022f47b825ab7aab.
Implementing it this way results in a bug where we show 2 badges. We would need to first update the forma component for EntryCard in order for us to pass scheduled state as a prop then we have to get rid of the icon for scheduled status completely
> chore: revert "fix: update status badge for scheduled entry (#1615)" [TOL-1801]

- cypress/component/rich-text/RichTextEditor.Tables.spec.ts
- cypress/component/rich-text/RichTextEditor.spec.ts
- cypress/component/rich-text/RichTextPage.ts
- packages/rich-text/src/Toolbar/components/ButtonRedo.tsx
- packages/rich-text/src/Toolbar/components/ButtonUndo.tsx
- packages/rich-text/src/Toolbar/index.tsx
Adding undo and redo buttons to rich text editors
https://contentful.atlassian.net/browse/TOL-1038
> feat: add rich text undo redo btns [TOL-1038]

- packages/rich-text/src/internal/hooks.ts
- packages/rich-text/src/plugins/Hyperlink/components/EntityHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/LinkPopover.tsx
- packages/rich-text/src/plugins/Hyperlink/components/ResourceHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/UrlHyperlink.tsx
- packages/rich-text/src/plugins/Hyperlink/components/useHyperlinkCommon.tsx
For some unknown reason (probably an internal slate bug), the provided `useFocused();` from slate-react is always false.
Instead of relying on this hook to determine if the editor is in focus, we check it ourselves.
I removed the hook for now since we only used it for the hyperlink modal
> fix: editor focus [ZEND-4737]

- packages/reference/src/__fixtures__/resource-type/resource-type.json
- packages/reference/src/__fixtures__/resource/resource.json
- packages/reference/src/common/EntityStore.tsx
- packages/reference/src/resources/Cards/ResourceCard.spec.tsx
- packages/reference/src/resources/Cards/ResourceCard.tsx
- packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx
- packages/reference/src/resources/MultipleResourceReferenceEditor.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.tsx
- packages/reference/src/types.ts
- packages/reference/src/utils/useSortIDs.ts
- packages/reference/stories/ExternalReferenceCard.stories.tsx
- packages/rich-text/src/plugins/EmbeddedResourceInline/FetchingWrappedResourceInlineCard.tsx
- packages/rich-text/src/plugins/EmbeddedResourceInline/LinkedResourceInline.tsx
- packages/rich-text/src/plugins/Hyperlink/useResourceEntityInfo.ts
- packages/rich-text/src/plugins/shared/LinkedBlockWrapper.tsx
- packages/rich-text/src/plugins/shared/LinkedInlineWrapper.tsx
- packages/rich-text/src/plugins/shared/utils.ts
Add support for external resources to the reference field editor.
* The biggest change is fetching _resource_ and _resource type_ entities as we’re extending the existing resource link logic and have already introduced the external resource card component in https://github.com/contentful/field-editors/pull/1602.
* Rich text doesn’t support external reference yet so the support is explicitly disabled. The changes here are only due to updated types.
> feat: support external resources in resource links

- packages/reference/src/__fixtures__/resource/resource.json
- packages/reference/src/resources/Cards/ResourceCard.spec.tsx
- packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx
- packages/reference/stories/ExternalReferenceCard.stories.tsx
Before we have the ideal state for the product card we should be able to show some crucial information that doesn’t fit with the ideal card UI. 
In the title section of the card, we need to make sure to show the Provider name (in our case `Shopify`) before the Product type name (`Product`/`Product Variant`/`Collection`).
In the description section of the externalCard we should show the Product ID as a subtitle then show the description if there is any.
> feat: add card subtitle and Provider ID to the external card [DANTE-1407]

- packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx
- packages/reference/stories/ExternalReferenceCard.stories.tsx
We want to enable selecting the external resource cards in the entity picker so we have to pass the `isSelected` option to the EntryCard.
> feat: enable isSelected option on the external resource cards [DANTE-1329]

- packages/reference/src/types.ts
Going forward we will use `urn` instead of `id` in external resources. The property is not used anywhere yet so changing the type now won’t break anything.
> feat: update external resource entity format

- packages/rich-text/src/plugins/Heading/components/ToolbarHeadingButton.tsx
- packages/rich-text/src/plugins/Heading/createHeadingPlugin.ts
We fired tracking events (`removeParagraph` and `insertParagraph`) when the user uses the Toolbar Heading Menu to select or deselect the paragraph element.
However, in user_interface we filtered out these events in the `ALLOWED_EVENTS`, since we do not care about tracking this. This caused errors to show in Sentry.
Removing the tracking at the source will fix the issue :)
> fix: remove paragraph tracking [TOL-1865]

- packages/reference/src/common/EntityStore.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
Previously we were seeing an infinite loader when the entries are deleted. Now showing the missing entry card instead
**before**
**after**
> fix: passing failed to fetched entry card when inaccessible []

- packages/reference/src/common/EntityStore.tsx
- packages/reference/src/index.tsx
- packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
follow up on https://github.com/contentful/field-editors/pull/1639
Currently, the rich text editor fails as we try to read 'contentType' from 'failed'.sys.
Instead patching the entry to 'failed', it uses now the status to check for errors
> fix(richtext-editor): handle failed inline entries [ZEND-4919,ZEND-4913]

- packages/rich-text/src/plugins/Table/components/TableActions.tsx
With LTR text actions dropdown goes to the right:
With RTL text actions dropdown goes to the left:
> fix: [] Consider text direction when positioning cell actions inside of Rich Text Editor

- cypress/component/reference/SingleResourceReferenceEditor.spec.tsx
- packages/reference/src/components/MissingEntityCard/MissingEntityCard.tsx
To fix the issue [here](https://contentful.atlassian.net/browse/ZEND-4949) where customers with no delete rights can delete references in an entry, this PR adds the correct check on `MissingEntityCard` to disable this bug.
> fix: add the isDisabled check to MissingEntityCard

- cypress/component/rich-text/RichTextEditor.Pasting.spec.ts
- packages/rich-text/src/plugins/DeserializeDocx/cleanHtmlEmptyElements.tsx
- packages/rich-text/src/plugins/DeserializeDocx/createDeserializeDocxPlugin.tsx
This pull request addresses an issue where spaces were removed from Korean text pasted into the rich text field. The problem was caused by the `cleanHtmlEmptyElements` plugin from Plate, which removes all empty elements, including `<span>` elements used by MS Word to represent spaces in Korean text.
Content support ticket: https://contentful.atlassian.net/browse/ZEND-5011
MS Word adds `<span>` elements for each Korean word, and spaces are represented by empty `<span>` elements. The `cleanHtmlEmptyElements` plugin removed these empty `<span>` elements, causing spaces to be removed in Korean text when pasted into the rich text field. 
We have customized the plugin to ignore empty `<span>` elements, ensuring that spaces in Korean text are preserved. This change means we no longer rely on the …
> fix: spaces removed for non english text [ZEND-5011]

- cypress/component/rich-text/RichTextEditor.Marks.spec.ts
- cypress/component/rich-text/RichTextEditor.Pasting.spec.ts
- package.json
- packages/rich-text/package.json
- packages/rich-text/src/Toolbar/index.tsx
- packages/rich-text/src/internal/types/editor.ts
- packages/rich-text/src/plugins/Marks/Strikethrough.tsx
- packages/rich-text/src/plugins/Marks/index.ts
Adding support for strikethrough based on the PR for superscript / subscript https://github.com/contentful/field-editors/pull/1280/files
> feat: support strikethrough

- cypress/component/reference/MultipleEntryReferenceEditor.spec.tsx
- cypress/fixtures/FakeSdk.ts
- cypress/fixtures/createRichTextFakeSdk.tsx
- packages/_shared/src/utils/entityHelpers.ts
- packages/reference/src/__fixtures__/FakeSdk.ts
- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
- packages/reference/src/common/customCardTypes.ts
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/rich-text/src/plugins/EmbeddedEntityInline/FetchingWrappedInlineEntryCard.tsx
- packages/rich-text/src/plugins/EmbeddedResourceInline/FetchingWrappedResourceInlineCard.tsx
- packages/rich-text/src/plugins/Hyperlink/useEntityInfo.ts
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedAssetCard.test.tsx
Restores the commented status calculation by locale, but only do it if the feature is enabled.
For the beta that comes as an instance parameter.
disabled here: https://github.com/contentful/field-editors/pull/1666/files
> fix: do new status calculation only conditionally [TOL-2143]

- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedResourceCard.tsx
- packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedAssetCard.test.tsx
- packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedEntryCard.test.tsx
- packages/rich-text/src/plugins/shared/__tests__/FetchingWrappedResourceCard.test.tsx
For rich-text the necessary properties were not provided to differentiate the entry status by locale
> fix(rich-text): add status differentiation props []

- packages/rich-text/src/plugins/Hyperlink/components/styles.ts
When creating spaces with "shift + enter" it breaks the line for normal text but doesn't for anchor tags. When rendered the rich text field is then render in apps it can contain the line break, safest to mimic the behaviour of normal text.
**Before**
**After**
> fix: adding line breaks to rich text anchor styles []

- packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx
External Resource Cards had no `onEdit` handler provided in the parent component, therefore clicking on the card had no effect. This PR fixes this issue and opens the URL provided in `externalUrl` (if existing).
https://contentful.atlassian.net/browse/DANTE-1734
> fix: add a missing handler for ERL click [DANTE-1735]

- packages/rich-text/src/RichTextEditor.tsx
To ensure that the reference package used is the same version as the rich text editor
> feat: wrapping connected rte instead of root one with entity provider []

- packages/rich-text/src/plugins/Normalizer/baseRules.ts
- Normalize the content before rendering it
- This will not trigger a change event for the editor directly
- The next time the content is adjusted and saved, it will be cleaned up internally
> fix(rich-text): changing scroll position with \r [TOL-2365]

- packages/reference/src/resources/Cards/ExternalEntryCard.tsx
- packages/reference/src/resources/Cards/ResourceCard.tsx
- packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx
In [this PR](https://github.com/contentful/field-editors/pull/1717) we have addressed the bug where clicking on an ERL card did not open the external resource. This, however, has introduced a bug where entity picker also started opening the links when selecting the cards.
This was caused by the fact that `ExternalResourceCard` component, used both by editor and entity picker, had the logic of opening a new tab.
Solution:
I lifted the logic of opening the URLs to a new parent component to be used only in the context of `field-editors` (entry editor). For context of entity picker (`experience-packages`), this logic is not there and click does not trigger opening a new tab.
> fix: add an ERL component to handle URLs in the editor [DANTE-1757]

- packages/reference/package.json
- packages/reference/src/common/EntityStore.tsx
- packages/reference/src/resources/Cards/ResourceCard.spec.tsx
- packages/reference/src/resources/ExternalResourceCard/ExternalResourceCard.tsx
- packages/reference/src/types.ts
- yarn.lock
Use proper types and methods from contentful-management for fetching [NER](https://www.contentful.com/help/orchestration/native-external-references/) entities.
Removing the default props in 49be1667ebce35dab86b31e46549d50779f5c4a2 is technically unrelated but it made sense to clean up while I was at it.
> fix: use proper methods to fetch NER entities

- packages/_shared/src/LocalePublishingEntityStatusBadge/ScheduledBanner.tsx
Fixed a ReferenceError caused by ScheduledActionTypes enum not being defined at runtime by removing the declare keyword from its definition.
> fix: reference-error by defining enum without declare [TOL-2454]

- packages/_shared/package.json
- packages/_shared/src/FieldConnector.test.tsx
- packages/_shared/src/LocalePublishingEntityStatusBadge/LocalePublishingPopover.tsx
- packages/_shared/src/LocalePublishingEntityStatusBadge/LocalePublishingStatusList.tsx
- packages/_shared/src/hooks/useAsyncLocalePublishStatus.spec.tsx
- packages/_shared/src/hooks/useAsyncLocalePublishStatus.ts
- packages/_shared/src/index.tsx
- yarn.lock
Bring in `useAsyncLocalePublishStatus` that can calculate the locale publishing status map for an entity. We will use this hook in the webapp and in other packages in field editors. Later on we might also use it in the entity search package.
⚠️ This is mostly copy-paste code from webapp
> feat: bring useAsyncLocalePublishStatus function [TOL-2454]

- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
- packages/reference/src/common/customCardTypes.ts
- packages/reference/src/components/EntityStatusBadge/EntityStatusBadge.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- localised entity status popover badge for reference cards (asset and entry)
- remove 'default' badge for references that are not localised. We don't need this anymore since here we will also show the stacked badge
- We pass `privateLocales` and `activeLocales` to the widget renderer using the widget API sdk props (internal).
- We also moved the `useAsyncLocalePublishStatus` fn to the `shared` package, so we can use it in the webapp and in the `reference` package to determine the locale status for each reference
> feat: implement localized entity status badge in references [TOL-2454]

- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
Bring localized entity status to the rich text editor (for embedded references)
> feat: localized entity status in rich text [TOL-2454]

- packages/slug/src/styles.ts
To prevent the overlap with the entity editor tabs stickiness introduced in https://github.com/contentful/user_interface/pull/23688.
---
Removing the `z-index` does not have any impact on the icon or spinner loader visibility.
> refactor(Slug): remove z-index to prevent overlap [CFISO-1949]

- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.spec.tsx
- packages/reference/src/components/CreateEntryLinkButton/CreateEntryMenuTrigger.tsx
Filter out experience type entries from the create new entry menu list in the reference editor
> fix: filter out experience entries [TOL-2503]

- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/Toolbar/components/StickyToolbarWrapper.tsx
Having the sticky entity editor tabs in the web app requires having a customizable offset for the Rich Text Editor sticky toolbar to ensure it stays visible when scrolling and not hidden behind the tabs.
**Before**
The toolbar is sticky behind the tabs.
https://github.com/user-attachments/assets/0935d43e-8582-42ab-bf84-2e0965126f82
**After**
Adding the offset value matching the tabs' height ensures the toolbar stays visible.
https://github.com/user-attachments/assets/b190189e-bc10-4da7-8b13-30bd5f49eb09
> feat(Rich Text Editor): add sticky offset property

- packages/_shared/src/utils/entityHelpers.test.ts
- packages/_shared/src/utils/entityHelpers.ts
- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
- packages/reference/src/common/customCardTypes.ts
- packages/reference/src/components/EntityStatusBadge/EntityStatusBadge.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
Exports a util function to calculate if the statuses differ. Controlled by `shouldRetainLocaleHistory`
> feat(shared): show stacked badge when status diff [TOL-2502]

- packages/reference/src/components/ResourceEntityErrorCard/FunctionInvocationErrorCard.tsx
I forgot to add `target="_blank"` to the function invocation error log link in the previous PR. This addresses that oversight.
> fix(reference): open function invocation error log in new window

- packages/date/src/DatepickerInput.tsx
Show the year dropdown picker again. from and to values are necessary to render it. increase the value to be able to go back to the year 1000
> fix: show dropdown datepicker [ZEND-5711, ZEND-5710]

- packages/rich-text/src/SdkProvider.tsx
- packages/rich-text/src/Toolbar/_tests_/toolbar.test.tsx
Rerender rich text editor when active locales change
> fix: rerender rich text when active locales change [TOL-2606]

- packages/markdown/src/MarkdownEditor.tsx
- packages/multiple-line/src/MultipleLineEditor.tsx
- packages/rich-text/src/RichTextEditor.tsx
- properly handle `isDisabled` props within RichText, Markdown, SingleLine, and MultipleLine editors
> feat: properly handle isDisabled prop [BBEE-797]

- packages/reference/src/resources/MultipleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/MultipleResourceReferenceEditor.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.tsx
- packages/reference/src/resources/useResourceLinkActions.ts
Checks permission when rendering to the Reference Editor. This check exists on the service, but we also want to check for access in the frontend for better UX. The same logic exists for "normal" same space entries.
> feat: permissions check for cross space reference editor [FUS-115]

- packages/reference/src/resources/SingleResourceReferenceEditor.tsx
[Removing](https://github.com/contentful/field-editors/pull/1818) the `apiUrl` prop caused a downstream consumer to break as it's expected by the general widget renderer of the web app. even though we don't use it here in the specific component, we have to allow it in the props.
> fix: re-introduce apiUrl prop [FUS-115]

- packages/_shared/package.json
- packages/reference/package.json
- yarn.lock
I need some types from `contentful-management@11.41.0` in `experience-packages` that consumes `@contentful#field-editor-reference` and `@contentful#field-editor-shared`
> chore: bump contentful-management version to 11.41.0

- cypress/component/rich-text/RichTextEditor.HR.spec.ts
- cypress/component/rich-text/RichTextEditor.Quotes.spec.ts
- cypress/component/rich-text/utils.tsx
Attempt to fix flaky RTE tests.
> test: [] Fix flaky tests

- packages/reference/src/common/EntityStore.tsx
- packages/reference/src/resources/Cards/ResourceCard.tsx
- packages/reference/src/resources/MultipleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.spec.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.tsx
- packages/reference/src/resources/useResourceLinkActions.ts
- packages/rich-text/src/helpers/config.ts
- packages/rich-text/src/plugins/EmbeddedResourceInline/FetchingWrappedResourceInlineCard.tsx
- packages/rich-text/src/plugins/Hyperlink/HyperlinkModal.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedResourceCard.tsx
Adds `locale` filter for reference search
> feat(field-dialog): filter by locale [FUS-199]

- packages/_shared/src/hooks/useActiveLocales.tsx
- packages/_shared/src/index.tsx
- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/rich-text/src/SdkProvider.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
- Extract `useActiveLocales` from experience packages to field editors shared, and change the type so it can accept both `EntitySelectorExtensionSDK` and `FieldAppSDK`
- Use this new `useActiveLocales` hook to determine the active locales instead of passing it as a instance param in field editors from the webapp
Later after this PR is merged: Use the now extracted `useActiveLocales` from field editors shared in experience-packages entity-search
> feat: use useActiveLocales hook instead of instance params [TOL-2887]

- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedAssetCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedResourceCard.tsx
Adding drag handle to embedded entities, if drag handle is provided then adding `draggable` to the `EntryCard` or `AssetCard` respectively, this makes them draggable in firefox.
> fix: dnd embedded entities in firefox [TOL-2460]

- packages/markdown/src/MarkdownEditor.tsx
- packages/markdown/src/components/MarkdownTabs.tsx
In this PR I update the `MarkdownEditor` component.
I add a new `forceTab` optional parameter. 
When given, this will force a specific tab to open and not allow the other tab to open. The disabled tab will also show the `not-allowed` cursor.
I am adding this, as the UI needed to for the '_editor_' tab to open when the AI Action is loading.
https://contentful.atlassian.net/browse/BBEE-1138
> feat: update markdown editor force tab to open [BBEE-1138]

- packages/markdown/src/MarkdownEditor.tsx
See previous [PR](https://github.com/contentful/field-editors/pull/1849) 
This change fixes a state issue in the previous PR. The issue was that the MD content was not re-rendering without setting the `selectedTab` state.
> feat: update markdown editor force tab to open p2 [BBEE-1138]

- packages/_shared/src/FieldConnector.test.tsx
- packages/_shared/src/FieldConnector.ts
- packages/reference/src/resources/testHelpers/resourceEditorHelpers.ts
The `FieldConnector` currently only relies on `isInitiallyDisabled` to determine the initial state for fields and is ignoring `sdk.field.getIsDisabled()`. This leads to sometimes wrong initial rendering if the `isInitiallyDisabled` is not passed
> fix(shared): base initial disabled state on `sdk.field.getIsDisabled()` [TOL-2914]

- cypress/component/reference/MultipleEntryReferenceEditor.spec.tsx
- cypress/component/reference/MultipleMediaEditor.spec.tsx
- cypress/component/reference/MultipleResourceReferenceEditor.spec.tsx
- cypress/component/reference/SingleResourceReferenceEditor.spec.tsx
- packages/reference/src/assets/WrappedAssetCard/AssetCardActions.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/reference/src/resources/Cards/ResourceCard.tsx
- packages/reference/src/resources/MultipleResourceReferenceEditor.tsx
- packages/reference/src/resources/SingleResourceReferenceEditor.tsx
References had some bugs with disabled state in the case where the field is disabled but we have permissions. This PR makes it so that any modifying actions (removing, moving, or adding) are disabled and/or hidden even if we have permission as long as the field is disabled
> fix: disabled state for references [TOL-2914]

- packages/boolean/src/BooleanEditor.tsx
- packages/boolean/stories/BooleanEditor.stories.tsx
- packages/dropdown/src/DropdownEditor.tsx
- packages/dropdown/stories/DropdownEditor.stories.tsx
- packages/list/src/ListEditor.tsx
- packages/list/stories/ListEditor.stories.tsx
- packages/multiple-line/src/MultipleLineEditor.tsx
- packages/multiple-line/stories/MultipleLineEditor.stories.tsx
- packages/number/src/NumberEditor.tsx
- packages/number/stories/NumberEditor.stories.tsx
- packages/single-line/src/SingleLineEditor.tsx
- packages/slug/src/SlugEditor.tsx
- packages/slug/src/SlugEditorField.tsx
- packages/slug/stories/SlugEditor.stories.tsx
- packages/tags/src/TagsEditor.tsx
- packages/tags/src/TagsEditorContainer.tsx
- packages/tags/stories/TagsEditor.stories.tsx
- packages/url/src/UrlEditor.tsx
- packages/url/stories/UrlEditor.stories.tsx
our field editors did not accept or forward an ID prop, which is a anti pattern for accessibility. Associating a label with an input field enables autofocusing of the associated input field when selecting / clicking on the label. 
fields could get, on accident, the same ID (when e.g. using an array index for id) which worsens the accessibility and violates HTML5 rules.
> feat: Improve Accessibility of field editors by enabling associating them with labels [UFO-1737]

- packages/reference/src/assets/WrappedAssetCard/FetchingWrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetCard.tsx
- packages/reference/src/assets/WrappedAssetCard/WrappedAssetLink.tsx
- packages/reference/src/common/MultipleReferenceEditor.tsx
- packages/reference/src/common/SingleReferenceEditor.tsx
- packages/reference/src/common/customCardTypes.ts
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/reference/src/entries/WrappedEntryCard/WrappedEntryCard.tsx
- packages/reference/stories/MultipleMediaEditor/MultipleMediaEditor.stories.tsx
- packages/reference/stories/SingleEntryReferenceEditor/SingleEntryReferenceEditor.stories.tsx
- packages/reference/stories/SingleMediaEditor/SingleMediaEditor.stories.tsx
This PR modifies several reference cards to allow rendering truly non-interactive cards. This is a prerequisite for [SPA-2702](https://contentful.atlassian.net/browse/SPA-2702)
[SPA-2702]: https://contentful.atlassian.net/browse/SPA-2702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: enable read-only assets and reference cards [SPA-2702]

- packages/_shared/src/hooks/useActiveReleaseLocalesStatuses.ts
- packages/_shared/src/utils/parseReleaseParameters.ts
- packages/rich-text/src/SdkProvider.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
Passing the correct params to the rich text embedded entry components so we can show the status badge in release entries
> feat: pass correct params to show release status [TOL-3103]

- packages/list/src/ListEditor.spec.tsx
- packages/list/src/ListEditor.tsx
Previously changes done via `sdk.field.setValue()` were not reflected in the editor
> fix(list): listen for external value updates

- packages/_shared/src/index.tsx
- packages/_shared/src/utils/determineReleaseAction.ts
- packages/_shared/src/utils/getEntryReleaseStatus.ts
- packages/reference/src/entries/WrappedEntryCard/FetchingWrappedEntryCard.tsx
- packages/rich-text/src/plugins/shared/FetchingWrappedEntryCard.tsx
Show the release status badges also for **entry based**
Approach
- migrates logic from user interface to field editors shared
- uses that logic to calculate the release action in rich text and reference package
> feat: show release action badge entry publishing [TOL-3103]

- packages/rich-text/src/RichTextEditor.tsx
- packages/rich-text/src/editor-overrides/index.ts
- packages/rich-text/src/editor-overrides/scroll-selection-into-view.ts
- packages/rich-text/src/internal/types/editor.ts
- yarn.lock
When you pressed "keydown + enter" soft line break in the web app we get an unexpected behaviour of putting the scroll position to the top. It has since been fixed in "slate-react" however we need to bump all plate + slate packages to ultimately introduce the fix.
This PR is overrides the offending prop for now until we get a chance to update the other packages
> fix: overriding scrollselectionintoview to stop scrolling []

- packages/reference/src/resources/MultipleResourceReferenceEditor.tsx
This locale argument is used by the ResourceEditor to add the `locale` parameter to the resource request, which provides locale context to the function resolving the external resource. 
This was correctly implemented for the `SingleResourceReferenceEditor` but we forgot to also do it for this field type.
> fix: pass locale argument to ResourceCard [FUS-746]

- .eslintrc.js
- tools/eslint-plugin-custom-lingui/index.js
- tools/eslint-plugin-custom-lingui/rules/enforce-translation-call-format.js
- tools/eslint-plugin-custom-lingui/rules/enforce-translation-call-format.test.js
Add new eslint rule to check format of lingui functions/macros `t` and `plural` as well as the `Trans` component.
The new rule only covers cases that are not yet handled by the existing key naming rule or TypeScript.
> chore: add eslint rule for translation format

- tools/eslint-plugin-custom-lingui/rules/enforce-translation-call-format.js
- tools/eslint-plugin-custom-lingui/rules/enforce-translation-call-format.test.js
- tools/eslint-plugin-custom-lingui/rules/enforce-translation-key-naming.js
- tools/eslint-plugin-custom-lingui/rules/enforce-translation-key-naming.test.js
Update our eslint rules for translation calls to cover Plural component macros.
* Check presence of `id` prop in Plural component
* Check key format in Plural component `id` prop
* Check message format in Plural component `other`, `one`, and `_0` props
* Check message format in plural macro `other`, `one`, and `0` arguments
> chore: update eslint rules for translation calls

- packages/reference/src/types.ts
More fixes of importing/exporting types from shared package:
See https://github.com/contentful/field-editors/pull/1925
> fix: [] Import and export type fixes

- packages/_shared/src/ReleaseEntityStatusBadge/ReleaseEntityStatusBadge.tsx
- packages/_shared/src/ReleaseEntityStatusBadge/ReleaseEntityStatusLocale.tsx
- packages/_shared/src/ReleaseEntityStatusBadge/ReleaseEntityStatusLocalesList.tsx
- packages/_shared/src/ReleaseEntityStatusBadge/ReleaseEntityStatusPopover.tsx
- packages/_shared/src/index.tsx
- packages/_shared/src/utils/getReleaseStatusBadgeConfig.ts
Make the following components internationalized:
Jira ticket: https://contentful.atlassian.net/browse/TOL-3432
✌🏼 Quick win: merge `RELEASE_BADGES` properties into `getReleaseStatusBadgeConfig` to avoid duplication
> chore: add i18n to ReleaseEntityStatusBadge and ReleaseEntityStatusPopover [TOL-3432]

- packages/rating/src/RatingEditor.spec.tsx
- packages/rating/src/RatingEditor.tsx
- packages/rating/src/RatingRibbon.tsx
The onClick event for some reason was buggy with my trackpad and may have been causing users issues, so I changed it to a more reliable onMouseDown as well as fixed a very minor warning about props
> fix: improve rating field usability with trackpad [ZEND-6961]

- packages/_shared/src/hooks/useReleaseStatus.ts
- packages/_shared/src/utils/getReleaseStatusBadgeConfig.ts
Reused a function that I created before (`getReleaseStatusBadgeConfig`) to ensure that labels from `useReleaseStatus` are correctly translated.
Ticket: https://contentful.atlassian.net/browse/TOL-3461
> chore: [TOL-3461] add i18n when createReleaseLocaleStatus
